project:
  type: website
  output-dir: docs

website: 
  reader-mode: true
  site-url: https://larrysfavoritemusic.github.io/Blog/
  description: 'A music blog type object'
  title: "Larry Loves Music"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: playlists.qmd
        text: Top Songs Playlists
      - text: Top Albums Lists
        menu: 
          - href: ./lists/2022_List.qmd
            text: "2022"
          - href: ./lists/2021_List.qmd
            text: "2021"
          - href: ./lists/2020_List.qmd
            text: "2020"
          - href: ./lists/2019_List.qmd
            text: "2019"
          - href: ./lists/2018_List.qmd
            text: "2018"
          - href: ./lists/2017_List.qmd
            text: '2017'
          - href: ./lists/2016_List.qmd
            text: '2016'
      
      - href: ListofBlogs.qmd
        text: Music Discovery
    right: 
      - icon: envelope
        href: mailto:larrylovesmusic@gmail.com 
      - icon: spotify
        href: https://open.spotify.com/user/1213285150?si=f5db32d6bd624952
  search:
    location: navbar
    type: overlay
      
  
title-block-banner: true       

format:
  html:
    theme: darkly
    css: styles.css
    toc: true  

editor: visual

