---
title: "Spotify Playlists"
page-layout: full
title-block-banner: true
---

Each year, in addition to my top albums, I make a top songs playlist as well (just in case people don't want to listen to \~25 albums....). These playlists allow me to share songs that I love that aren't necessarily in any of the top albums or only are released as singles.

Typically the playlists consist of 100 songs, ranked from 1-100. In 2018, because I chose 40 albums rather than 10 or 25, I decided against a making top songs playlist. Additionally, for 2016, I did not make a top songs playlist as it was my first ever list. However, for both 2016 and 2018, I made 25 song playlist to showcase some of my favorite songs from those years. Lastly, I also made a playlist for my favorite song of the 2010s.

# 2024

1.  [Kingdom Come - Cindy Lee](https://youtu.be/_LJi5na897Y?si=3xtPSZqcTsPx-2jZ&t=2165)\*\*

2.  My Golden Years - The Lemon Twigs

3.  Toro - Remi Wolf

4.  Death & Romance - Magdalena Bay

5.  Right Back to It - Waxahatchee & MJ Lenderman

6.  obsessed - Olivia Rodrigo

7.  Gemini - Angélica Garcia

8.  Empire Never Knows - Jessica Pratt

9.  The Calm That Keeps You Awake - Knocked Loose

10. Rattlesnake - Rubblebucket

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/1qIl4nAq5LD2Fi8U9losOs?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
\*\*Kingdom Come can only be found on bandcamp or youtube.

# 2023

1.  Blomi - Susanne Sunfor
2.  The Clutch - Palehound
3.  Bull Believer - Wednesday
4.  Swing (In A Dream) - Squid
5.  Soft Landing - Billy Woods and Kenny Segal
6.  Fire the Editor - James Blake
7.  kisses - Slowdive
8.  2000 Miles - Jolie Holland
9.  Mitski - I Don't Like My Mind
10. Garbage Pale Kids - JPEGMAFIA and Danny Brown

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/0PywVGo37UYQqobfGUsHJ9?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
# 2022

1.  The Place Where He Inserted the Blade - Black Country, New Road
2.  High Hopes - Sweet Pill
3.  Gold Chain Punk (whogonbeatmyass) - Soul Glo
4.  Sugar/Tzu - Black Midi
5.  Expert In A Dying Field - The Beths
6.  All The Good Times - Angel Olsen
7.  Basketball Shoes - Black Country, New Road
8.  God Turn Me Into a Flower - Weyes Blood
9.  Summer Dream - Bonny Light Horseman
10. Satan - Andy Shauf

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/4FHnWCczoYevM2M6DTdV2v?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
# 2021

1.  G.S.K - Squid
2.  Be Sweet - Japanese Breakfast
3.  MMMOOOAAAAAAYAYA - illuminati hotties
4.  Romeo - Jungle feat Bas
5.  Orange - Pinegrove
6.  Pocket Square Mother Fucker
7.  Holocene - Zella Day feat Weyes Blood
8.  Write A List of Things to Look Forward to - Courtney Barnett
9.  Delicious Things - Wolf Alice
10. Secrets (Your Fire) - Magdalena Bay

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/5ufXFtIXpYXFBXKqGqN1eG?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
# 2020

1.  Will Call - Brass Tracks feat Elliott Skinner, Victoria Canal
2.  Kyoto - Phoebe Bridgers
3.  Held Down - Laura Marling
4.  Home - Caribou
5.  Heavy Metal - Cindy Lee
6.  The Alarmist - Pinegrove
7.  Sympathy for the Baby Boo - Deerhoof
8.  free ppls - illuminati hotties
9.  Living Room - Andy Shauf
10. Selling Candy - Ohm (now called Fionom)

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/4BBP8JJgfNq8H25V8stCFB?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
# 2019

1.  Hope - Alex G
2.  Chance - Angel Olsen
3.  Century - Big Thief
4.  Don't Miss It - James Blake
5.  Morbid Stuff - PUP
6.  Faith - Bon Iver
7.  A Lot's Gonna Change - Weyes Blood
8.  An Empty Corner - Wilco
9.  Replaced - Big Thief
10. Terlingua Girl - Lillie Mae

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/4ffCWw6yXdCaTU9PM1YSJK?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
# 2018

1.  Beach Life-In-Death - Car Seat Headrest
2.  Mither - Bill Ryder-Jones
3.  Rings - Pinegrove
4.  City Looks Pretty - Courtney Barnett
5.  Lemon Glow - Beach House
6.  Great No One - The Beths
7.  Almost Had to Start a Fight/In and Out of Patience - Parquet Courts
8.  To Be - Fox Warren
9.  Nevermine - Fourth Wanderers
10. 6 Summers - Anderson .Paak

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/5LG7vPzO2U3w453BfkxtR3?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
# 2017

1.  Sugar for the Pill - Slowdive
2.  Bet She Looks Like You - Nick Hakim
3.  Mythological Beauty - Big Thief
4.  Thinking of a Place - The War on Drugs
5.  Driver - John Andrews & The Yawns
6.  Baybee - Jay Som
7.  Continental Breakfast - Courtney Barnett, Kurt Vile
8.  Saturnz Barz - Gorillaz feat Popcaan
9.  Shark Smile - Big Thief
10. Die Young - Sylvan Esso

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/4fsurEdMqyxifShZY9c0qI?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
# 2016

1.  The Magician - Andy Shauf
2.  Vincent - Car Seat Headrest
3.  Hostage - Klangstof
4.  Sister - Angel Olsen
5.  Hidden Driver - LVL UP
6.  Martha Sways - Andy Shauf
7.  The Devil and his Anarchist Surrealist Retinue - Deerhoof
8.  Foreplay - Jalen Santoy
9.  It's Getting Late - Honeysuckle
10. Real Love - Big Thief

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/34Qo9oOPh5pDDvtUrsAlUL?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
# 2010s

1.  How Long Must I Wait - Dr. Dog
2.  I Love You, Honeybear - Father John Misty
3.  Gimme All You Love - Alabama Shakes
4.  Feels Like We Only Go Backwards - Tame Impala
5.  The Magician - Andy Shauf
6.  Sugar of the Pill - Slowdive
7.  Pedestrian at Best - Courtney Barnett
8.  Shark Smile - Big Thief
9.  Hope - Alex G
10. Vincent - Car Seat Headrest

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/6EXEQs8BQa888Z0aF0TxfI?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
