---
title: "My Favorite 10 Albums of 2016"
format:
  html:
    code-fold: true
editor: visual
---

This is the list that started it all: made from a undergrad who wanted to stay entertained during finals week. Despite this being my first list, I'm impressed with how well it's held up. The music quality in 2016 was just amazing, with amazing albums I don't cover here that include (and are not limited to) David Bowie's final record "Blackstar", Anderson Paak's "Malibu", Frank Ocean's "Blonde", Pinegrove's "Cardinal", and Deerhoof's "The Magic" (which remains my favorite album of theirs from a very long and impressive catalog). The albums that are on this list still find their way into my listening queues on fairly regular basis. I also didn't make a top songs playlist to accompany the album list so I'll name a handful tracks that remain favorites to me, but tracks that really stand out to me from this year include:

-   Andy Shauf's haunting opening track "The Magician"

-   The controlled chaos that is Car Seat Headrest's "Vincent"

-   The incredibly catchy jazz rap from Jalen Santoy, "Foreplay"

-   The country/bluegrass layered in harmonies, "It's Getting Late" by Honeysuckle

-   The indie rock ear worm combined with subtly great guitar work, "Emotions and Math" from Margaret Glaspy

-   Ripping guitars and emotional vocals on "Real Love" from an excellent debut from Big Thief (keep an eye on these guys)

-   The euphoric slow burn on "Hidden Driver" by LVL Up

-   Finally, the delightful track from a one off project super group project named case/lang/veirs, "Atomic Number"

Plus tons of other songs, some of which I feature in this list. This

## My Favorite Songs of 2016

1.  The Magician - Andy Shauf
2.  Vincent - Car Seat Headrest
3.  Hostage - Klangstof
4.  Sister - Angel Olsen
5.  Hidden Driver - LVL UP
6.  Martha Sways - Andy Shauf
7.  The Devil and his Anarchist Surrealist Retinue - Deerhoof
8.  Foreplay - Jalen Santoy
9.  It's Getting Late - Honeysuckle
10. Real Love - Big Thief

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/34Qo9oOPh5pDDvtUrsAlUL?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 10. Lucy Dacus: No Burden

This would serve to be a really solid debut for Lucy Dacus, going on to create music that would make it on to my future lists. The album is full of introspective lyrics like on "I Don't Wanna Be Funny", which talks about her wanting to be more than just a funny person. But as far as I'm concerned, Lucy's biggest strength is her soothing voice, which enhances her words. "Map on the Wall" serves as a nice slow burn track, helping to fill out the rest of the album. All in all, a really great debut.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/7lQ9R31OcTvMn2MojAuKVE?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Green Eyes, Red Face, Map on the Wall

## 9. RY X: Dawn

At the time of writing this, I honestly hadn't listened to this record in quite some time. Going back and listening reminded me what I saw in this album. This record is filled with lush strings and subtle beats, topped off with Ry Cuming's gentle vocals. In particular, "Howling" has this simple little bit and yet does so much to make the song an earworm. "Berlin" remains a super hit for this artist (179 million streams on spotify) and probably the best vocal performance on the record as Ry's voice matches the guitar note for note in the background. A true highlight is the gorgeous "Beacon" led by the an orchestral string section the builds with guitars and percussion in the background. This album serves as a perfect late-night companion, and one that likely will find myself spending time with in the future.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/0DvauBOn2G8RIEQR54Cmiv?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Beacon, Howling

## 8. Klangstof: Closure

I have yet to find anything that sounds quite like this record. The dutch trio melds together electronic and indie pop together to create dreamy landscape, filled with songs with slow-burns. This album opens strongly with the meloncholy instrumental track "Doolhof" with ringing guitars and plenty of bass, setting the scene for the rest of the album. "Hostage" is this amazing slow-burn track starting off as a modest alt-pop with subtle guitar and electronic drum kit before evolving into an expansive dream-pop climax. "Island" perfectly closes out the record with another slow build up, starting with a catchy beat and vocal melody while constantly building on the current song. Before you know it, you find yourself surrounded by synths and echoing guitars. This album remains a classic for me, and honestly a pretty cool find for this just being my first official list.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/314g2JtzkHhPw8uo6lrAwz?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Hostage, Island

## 7. Angel Olsen: MY WOMAN

MY WOMAN is the record I discovered the artist that would become one of absolute favorite artists, Angel Olsen. This album follows the absolutely amazing "[Burn Your Fire For No Witness](https://open.spotify.com/album/62RDt42wD8VdrhfHG6IzpC?si=74W4z9mlRg-q9Dqk1dCGvQ)", which by in large was Angel Olsen's breakout hit, and really outdoes herself. The album starts off with this incredible "Intern", containing nothing but a synth and Angel's iconic voice, before transitioning into the almost rockabilly "Never Mine". If this album really demonstrates anything, its Angel's ability to craft a well paced tracklist, with the front end filled with singles (including the lead single "Shut Up Kiss Me"), with the back end containing more B-side tracks like the dreamy "Those Were the Days". The track "Sister" remains as one Angel's best songs, with the front half containing a relaxed ballot that Fleetwood Mac would have been proud of, before building to a soaring guitar solo. This was a statement from Angel, not only in that she has the ability to change up her sound, but that she was going to be one of the most consistent songwriters in music.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/3CHcldbsbrBOOlw8cnLpNm?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Sister, Never Be Mine, Shut Up Kiss Me

## 6. Wilco: Schmilco

Anyone who knows me knows that Wilco is my favorite band. So any review I write about them should probably be taken with a grain of salt. That being said, this album is criminally underrated in the Wilco catalog. This album only came a year after the well received "[Star Wars](https://open.spotify.com/album/5yHC5HGL7CbdbzgqSzuaoP?si=F42eW_n0RNC485X5WZKqrw)" (an album title that was meant stir up a lawsuit that never materialized), containing tons of fun songs with fuzzy guitars, loose arrangements, and lackadaisical vocals from Jeff Tweedy. "Schmilco" follows a completely opposite formula, with tight arrangements, a minimalist approached, and some of Jeff's most introspective lyrics to date. The album opens with "The Normal American Kids", only featuring an acoustic guitar with lead electric flourishes and Jeff's voice, exploring his frustration as an and drug use as an adolescent. "If I was Ever a Child" is reminiscent of the alt-country ascetic of "Being There". "Locator" is an experimentation into a minimalist noise rock song, giving the album some sonic range. I love the very simple guitar/piano melody and almost whispered vocals on "Shrug and Destroy" that just set this wonderful hushed mood. Anything Wilco releases will immediately be compared to there legendary works from the late 1990s into the 2000s, which I think does a disservice to the albums individually. Turns out, even if a record isn't a band's best work, if you are as talented as Wilco, its still going to be pretty damn good.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/1Wjheru5k9DMQduRIasAyL?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** If I Ever Was A Child, Locator, Shrug and Destroy

## 5. Keaton Henson: Kindly Now

Words cannot describe how fragile and bleak this album is. Henson gained a cult following on is fantastic debut "[Dear](https://open.spotify.com/album/11gZYT85Mx4aSiHthMYLLQ?si=nqKiqDxYSvyFKRRw92R9Dg)", that contained largely guitar only tracks like "You Don't Know How Lucky You Are". Here, Henson opts for more piano driven tracks, bulstered by orchestral sections. Keaton Henson writes a truly beautiful song that can be difficult to get through. Much of the lyrical content is centered around a particularly painful break up and missing this person. The "Pugilist" starts similar to tracks on "Dear" before growing into the much larger sound that you come to expect from the rest of the album On "Alright" Henson talks about how he's managing without this person, or lamenting losing this person on the closing track "How Could I Have Known", that swells into emotional orchestral finale. This album is filled a lot of pain, but for those who can stand it, or those who just want bawl their eyes out, there is a lot of beauty to be found.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/2STN4lLvNNRsO0FuatKqVI?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Holy Lover, Alright, I Should Have Known

## 4. Margaret Glaspy: Emotions and Math

Coming back to this album, it's pretty amazing how bare-bones this whole record is, with the tracks being buoyed by Margaret's strong vocals and guitar melodies that just get stuck in your head. Every time I listen to "You and I" and can't help hum along to the guitar part. She really shows off her guitar chops on "Memory Street", ripping her way through a blues solo. The true stand out is the title track "Emotions and Math" with yet another catchy little riff played on the low E string and probably Margaret's best vocal performance on the entire album. The simple studio approach to this album really allows the song writing stand on its own and I think is a real strength. A really impressive debut record from Margaret Glaspy.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/2Bq3X3NF39gvmAihzX1DdK?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Emotions and Math, You and I, Memory Street

## 3. Bon Iver: 22, A Million

On this list, albums 2 and 3 are essentially tied, which made picking their spots all the more difficult. We first start off with Bon Iver's "22, A Million", after 5 years since the breathtakingly beautiful self title record from 2011. That previous record in addition to the EP "Blood Bank" hinted at the experimentation Justin Vernon would eventually lean into. "22, A Million" is nearly unidentifiable from the debut "For Emma, Forever Ago", drenched in reverb, autotune and dissonance. And yet, despite all these tricks, the album somehow remains authentic and organic, particularly on the rare occasions when just Justin's unulterd voice appears. It's a bit difficult to point out individual tracks as this album really doesn't contain very many fully developed songs. Instead, tracks largely bleed into each other, sometimes making it difficult to tell if there was song changed. Really, this album is truly best enjoyed all in one sitting. A major standout for me is "715 - CRΣΣKS" (man these are a pain to type out) showcasing just the autotuned harmonies of Justin, that use the spaciousness of the song to its advantage. "8 (circle)" is almost sounds like a something high schoolers would slow dance to in 80s and contains this amazing horn section at minute 3 that I adore. The album ends with "00000 Million", grounding us as it strips back most of the crazy production leaving behind just choir of vocals and a standup piano, and I just find incredibly comforting. Perhaps the greatest strength of this record is Bon Iver finding ways to push the limits of his sound without losing what makes his music great.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/4bJCKmpKgti10f3ltz6LLl?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** 715 - CRΣΣKS, 8 (circle), 00000 Million

## 2. Car Seat Headrest: Teens of Denial

As far as I'm concerned, there is no one in indie rock that is as ambitious as Will Toledo of Car Seat Headrest. I don't mean in the sense of him being sonically adventurous or genre breaking but just huge is albums, with Teens of Denial being his masterpiece. For starters, this album contains not 1 but 2 \~10 minute ballads on the B-side of the record which I think really captures how hard Will was swinging for the fences. A major theme throughout the record is teenage agnst and the drug and alcohol use that often pairs with it. The album opens strong with punchy "Fill in the Blank" a track that could have been written by the Ramones before easy into the albums centerpiece "Vincent". Vincent is such insane song, starting with just a ringing guitar, building tension and slowly loses control in chaotic climax. Immediately after, the album transitions in the heavy power chords on "Destroyed by Hippie Powers" which just kicks absolute ass. Another highlight is the the anthem against drunk driving "Drunk Drivers/Killer Whales" (though I never figured out what the killer whale is in reference to...). The Ballad of Costa Concorida is the second of the two ballads on the back end of the album that starts slow (with an interesting reference to Didos "White Flag") before erupting into a grand finale. The ambition on this record is honestly a breath of fresh air and reminder that there is still life within the genre of rock.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/3KpYyDP8q8sUBxatHaYEsP?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Vincent, Drunk Drivers/Killer Whales, The Ballad of the Costa Concodria

## 1. Andy Shauf: The Party

This album holds a really special place in my heart. Andy Shauf is someone I listened to obsessively throughout college (so much so I was seriously considering driving to Toronto from Eastern NY to see him play the day before Thanksgiving), and was because of this album. The album contains incredibly lush arrangements including clarinets and strings, with every instrument (excluding the strings) being played by Shauf himself, allowing Andy to control every detail of the record. "The Party" is a concept album based around events at house party (but not necessarily during the same night). Andy Shauf's soft voice serves as a perfect narrator to follow different individuals and exploring their thoughts or feelings. Feelings that people are to familiar like being jealous of how out going someone is (Eyes of Them All) or drunkenly embarrassing yourself (Twist Your Ankle). The album also follows two characters, Sherrie and her love interest Jeremy. "Early to the Party" follows Sherry, arriving awkwardly early to a party, with Andy perfectly captures the uncomfortable feelings behind this. On one of my favorite tracks on the album "To You", Sherry uncomfortably attempts to share her feelings to Jeremy only to for her to back down. The Party even has real drama, with the track "Alexander All Alone", Alexander collapses dead outside while smoking a cigarette (and oddly enough increases the body count on Andy Shauf records to 4). The album of closes perfectly, with "Martha Sways" as the narrator slows dances with Martha at the end of the party that reminds him of someone else, with lush strings bringing him (and the listener) into a daydream. The song closes with the lines "Martha Spins, and I catch her hand. She smiles and laughs, bringing me back" snapping us out of the daydream. It one of my very favorite music moments. I cannot express how much I love this album and as such, I chose it as my album of the decade for the 2010s.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/35FWLG8Ysjj1BF3sx4F6zM?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks**: The Magician, To You, Martha Sways, Early to the Party
