---
title: "My Favorite 10 Albums of 2017"
format:
  html:
    code-fold: true
---

My second ever top albums list fell on my junior and senior years at ESF. I was pretty happy with how my first list came out (1s of people thought it was pretty cool), so I spent more time looking for more new music. This was also the year that I got my first record player and my first 4 vinyls which included:

1.  Andy Shauf's The Party
2.  Wilco's Yankee Hotel Foxtrot
3.  Jeff Buckley's Grace
4.  Gregory Alan Isakov's The Weatherman

A pretty great collection if you ask me. I also was off a great senior year of soccer, going undefeated in our league leading to a trip to nationals (where I would score two goals!). In general, my life was going pretty good. For this list, I was still trying to stick to 10 albums, which inevitably made led me to leave some albums I really enjoyed off. To remedy this, I included 4 honorable mentions. I also made my first top 100 songs playlist as well, and frankly, I think its pretty damn good, especially the number 1 pick "Sugar For the Pill" which remains one of my favorite very songs from the 2010s. This ended up being a pretty great soundtrack for my final year at ESF.

## My Favorite Song of 2017

1.  Sugar for the Pill - Slowdive
2.  Bet She Looks Like You - Nick Hakim
3.  Mythological Beauty - Big Thief
4.  Thinking of a Place - The War on Drugs
5.  Driver - John Andrews & The Yawns
6.  Baybee - Jay Som
7.  Continental Breakfast - Courtney Barnett, Kurt Vile
8.  Saturnz Barz - Gorillaz feat Popcaan
9.  Shark Smile - Big Thief
10. Die Young - Sylvan Esso

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/4fsurEdMqyxifShZY9c0qI?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## Honorable Mention. Sylvan Esso: What Now

Few bands make me smile as much as Sylvan Esso. I was also super disappointed to leave this album off the top 10 list, and was the major reason why I included some honorable mentions. This is the followup to their amazing [self-titled](https://open.spotify.com/album/1862qnxqsLeiNDblknjtiL?si=6NNOp_CnSoy7Wlygx1tv5w) album, a clever indie-electronica album that sets the apart from other electronic artists. "What Now" is poppier and than its predecessor, perfectly epitomized by the brightly colored track "The Glow". "Die Young" is a certified banger, detailing the annoyance having to hold off dying young because they found love. "Signal" is great pop anthem that's worth blasting in your car with the windows rolled down. At it's core, Sylvan Esso made an album chock full of great songs that ends up with the whole being greater than the sum of its parts.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/1BJMCEXQ7JmuVlJ6cYbe3x?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks**: The Glow, Die Young, Signal

## Honorable Mention. Kendrick Lamar: Damn

If there is only one major problem with this album, is that is had to follow up the masterpiece that is "To Pimp A Butterfly". Even so, Kendrick sticks that landing with the follow up on "DAMN" (I'm not really counting "Untitled Unmastered, as it's really a collection of b-sides, which have no business being as good as they are). At this point, Kendrick has really solidified himself as one the greats in Hip Hop, and this album contains so much of that confidence on tracks like"DNA". My absolute favorite is the closing track "Duckworth", detailing the crazy coincidence of his father Duckworth meeting Top Dawg many years prior to Kendrick signing for his label.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/4eLPsYPBmXABThSJ821sqY?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Duckworth, DNA, Humble

## Honorable Mention. Alex G: Rocket

This was the first Alex G album I was introduced to and was immediately intrigue. This album contained so many types of sounds that seemed like they wouldn't fit together; americana and traditional american folk combined with electronic and industrial music. It makes for a pretty unique listen, which kind of describes every Alex G album. "Powerful Man"is a bizzarely sweet song with an ear-wormy guitar. "Judge" as a sort of grundge/Elliot Smith vibe to that I really enjoy. Then there's "Brick" which feels like it doesn't belong at all on the record, and I'll leave to you to listen to. It's not a perfect album, but the positives far out weight the negatives.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/5Pq92omNLyQgGGrj2u4pur?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Powerful Man, Proud, Judge

## Honorable Mention. Father John Misty: Pure Comedy

This album frustrates me to no end and was a fairly polarizing release for Father John Misty fans. There is so much great songwriting and vocals performances on this record that I'm always happy to talk about, such as the breadth of topics on the title track including human brains being to big to birthed at full size, ending on the great line "I hate to say it, but each other is all we got". Or the beautiful country-esque ballad on "Smoochie", describing someone comforting John (or Father John?). And yet, John gets in his own way with these endless self-indulgent tracks like "Leaving LA" or "So I'm Growing Old on Magic Mountain". These problems really prevent an good album from becoming a great album despite the numerous great songs. Still, I enjoy much of this project, which was enough to warrant an honorable mention, evening if I grumble about it.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/6nyf9D2M4je5BdNXwycoIe?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Pure Comedy, Smoochie, Ballad of a Dying Man

## 10. Jay Som: Everybody Works

We were a few months in 2017, and I was a getting a bit frustrated at the lack of enjoyable indie-rock albums that had been released so far. Enter Jay Som's "Everybody Works". This album is fantastic collection of just great indie-rock song writing. The track "Baby" has one of the vibest introductions to it, and I'm in love with the guitar tones throughout. "Bus Song" was a breakout hit for Jay Som, containing bright lyrics and horn section (and I so here for the positivity towards public transportation). The album closes strongly with the woozy "For Light", with distorted vocals and a bright guitar towards end of the track. This album was perfect to end the indie-rock mini-drought I was experiencing in 2017, and holds up really well today.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/1ZMtgC7o6TGbzwkv5SpThU?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 9. The War on Drugs: A Deeper Understanding

This is far and away my favorite War on Drugs record. There aren't too many guitar led albums left in this day age (which isn't necessarily a bad thing), and even fewer bands who do it better. There is just so much incredible melodic guitar throughout the record on tracks like "Pain" (containing the great line "I resist what I cannot change") or "Strangest Thing". However, the true masterpiece lies on the 11 minute "Thinking of A Place", that is just perfectly suited for long drives through the desert. If your a fan of getting lost in some great guitar rock, this record is for you.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/4TkmrrpjlPoCPpGyDN3rkF?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Thinking of A Place, Pain, Strangest Thing

## 8. Fleet Foxes: Crack-Up

The Fleet Foxes have this unique ability to make epic folk records, and "Crack-Up" is probably their most ambitious effort. This album is a bit dense, with very few standout singles or songs that stand alone without the context of the record. The album is lush with sweeping strings, grand harmonies, and driving acoustic guitars, an album fit to be a soundtrack to a journey around the world. "Third of May" is a perfect distillation of the entire record, with Robin Pecknold's soaring vocals standing out wonderfully throughout the track. "Fool Errand" is an instant classic that contains some of my favorite harmonies from the Fleet Foxes (which is really saying something). The album closes perfectly with the title track, serving as the finale to the epic journey this album takes you on. "Crack-Up" may not be as accessible as other records by the Fleet Foxes, but it rewards you for the time you put into it

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/0xtTojp4zfartyGtbFKN3v?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks**: Fool's Errand, Third of May/Odaigahara, Crack-Up

## 7. Wolf Alice: Visions of A Life

Wolf Alice is a band that loves a big sound on all of their records and this is no exception. The album begins with the with the dreamy stadium rock track "Heavenward", with Ellie Rowsell hypnotic vocals and hazy guitars, before transitioning into the noise-rock "Yuk-Foo". I really enjoy the snappy guitars and fun vocal performance on "Beautifully Unconventional" which is an really fun track. The album closes with the emotional climax of the record, the title track, containing big shoe-gazy guitar solos, to end the album on a high.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/7BJmbXNSX1tUPmVjvrlqvz?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Heavenward, Beautifully Unconventional, Visions of Life

## 6. Courtney Barnett and Kurt Vile: Lotta Sea Lice

This was a collaboration that I wasn't expecting but honestly makes perfect sense. Courtney and Kurt's musical styles compliment each other very well with their casual vocal performances and guitar driven songwriting. There aren't too many original songs on the record but the ones that are there a truly fantastic. "Over Everything" is a perfect jam that fits perfectly to a soundtrack for the summer. "Continental Breakfast" is a cute song discussing the continental friendship that Courtney and Kurt have made, and just makes me plain happy every time I hear it. They also cover each other's songs with Kurt covering the classic "Out of the Woodwork", while Courtney covers "Peepin Tom" (a version that I prefer, despite loving the original). Ifound myself playing this album a lot, especially when I was in a good mood. These two set out to make a fun and pleasant record and they succeeded. Sometimes, that's all an album needs to be.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/3gvo4nvimDdqA9c3y7Bptc?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Continental Breakfast, Over Everything, Peepin' Tom

## 5. Peter Silberman: Impermanence

An aspect of music that I really enjoy when it's done well is the use of spaciousness, particularly when it emphasizes something within the music like a melody or to highlight a lyric. "Impermanence" takes this to another level. Peter Silberman (famously of the Antlers and creator of one of the most tragic records ever made "Hospice") recorded this album after recovering from hearing loss in one ear. This hearing loss inspired him to take a minimalistic approach with just faint touches of guitar, syntths, and his angelic voice. "Karuna" is my favorite, as it opens with just the occasional strum of the guitar and Peter's powerful vocals before building ever so slightly to include more involved guitar work and just a bit of drums. "New York" explores Peter's noticing and being overwhelmed by noises in New York City that he once took for granted. The album closes as it should, with simple ambient track on "Impermanence". This is a such unique project that tries to explore the loneliness of deafness with sound (or the lack there of). It may be a bit difficult for some people to get into it due to its spareness, but incredibly rewarding if you spend time with it.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/3sR2dXUyecxOsoB8WgQQZd?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Karuna, New York, Ahimsa

## 4. Slowdive: Slowdive

The only dream-pop record to rival Beach House, comes from a band that was popular in the 90s before taking a 2+ decade hiatus. This album is just a masterclass it what makes dream pop so amazing, with bright melodic guitars, hushed and reverbed vocals, and an overall melancholy feeling behind it all. The album opens wonderfully with "Slomo" that have the two vocalists intertwining their voices as the ringing guitar envelopes them. "Star Roving" is a perfect track to zip down the highway to at night with the driving percussion and fuzzy guitars. But the absolute highlight is the masterpiece "Sugar For the Pill". The ringing guitar melody that plays at the start and throughout the track is guaranteed to stick in your head, as the song exhibits cascading guitars before building to the incredibly climax towards the end of the song. The album closes with the beautiful piano ballad on "Falling Ashes", a nice contrast to the rest of the album. This a perfect soundtrack to any late night driving or staying up late for school or work. It's amazing that a band can take such a long hiatus only to create arguably their best work. I hope to hear more from them in the future (and maybe in less than two decades).

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/4nSWX5A4xVomzrOEGDKLQ6?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Sugar for the Pill, Star Roving, Don't Know Why

## 3. Feist: Pleasure

Feist became a bit of a superstar in the 2000s with her hit album the Reminder and the mega hit "1234", which is fairness is great music. However, "Pleasure" is far and away her best work. Another album that uses space incredibly well, she somehow finds a balance between delicate and badass, which is an difficult needle to thread. On many occasions, Feist inverts a typical song structure where the quietest parts are reserved for the chorus. Her use of dynamics make the album exciting as it can go from loud to quite to loud again at any moment. On "I Wish I Didn't Miss You", the guitar is strummed almost percussively that along with vocal effects, give the track a bit of a bite. There is tons of great guitar work throughout the album like on tracks like "I'm Not Running Away" and the title tracks. Perhaps the coolest moment on the album is the transition of "Any Party" into "A Man is Not His Song", which then closes with a brief moment of metal in the background. Feist has produced a lot of really great music, but this album takes the cake. An album that I just find criminally underrated.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/5lXgrzp3xcFdYCQXtsS6dG?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** I Wish I Didn't Miss You, Any Party, A Man is Not His Song, Young Up

## 2. Nick Hakim: Green Twins

On his previous two EPs, Nick Hakim managed to make these lovely, sleepy R&B tracks (highlights include "Cold" and "I Don't Know"). "Green Twins" however, would be a big departure from this and the basis for a lot of his music to come. The record is the experimental, psychedelic R&B and Soul record that is filled with ambitious song writing and truly amazing production. The title track is a great example with a drum kit and fuzzier guitars as Nick's vocals a drenched in reverb. The guitars come in full force towards the end of the track which just makes the song hit that much harder."I Bet She Looks Like You" has this great ringing electric guitar part that evolves into a deliberately messy guitar solo that made it one of my favorite songs of the year. "Cuffed" has a great drum beat to it that makes the track feel almost like a jam, and has this really cool slowdown towards the end of track. The B-side of the record, Nick leans more into the production like on tracks "Miss Chew" and "The Want", filled with layered harmonies and wacky vocal effects. The production on this record is just top notch and it gives so much personality to it, and you'd be hard pressed to find albums that do it better.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/5RfZQHPapcSY40HaYvt3fh?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** I Bet She Looks Like You, Cuffed, Green Twins, Miss Chew

## 1. Big Thief: Capacity

The album that made me fall in love with Big Thief. This band has become so important in my life and few artists are as consistent of songwriters as Adrianne Lenker (or efficient in their output). "Capacity" came dropped only a year after the incredibly well received debut album "Masterpiece" and solidified them as one of the best acts in indie rock. There is just so much incredibly songwriting and band arrangements throughout the track list, and some of Adiranne's best lyrical work. "Pretty Things" opens the album with this a mysterious acoustic part exploring complicated feelings in femininity and masculinity during sex. Immediately following is truly wonderful "Shark Smile" that starts off with tumultuously before simply to a driving rhythm guitar part. The song details two young lovers right up until a car crash that kills just one. There is this amazing little guitar solo that Buck Meek does on this track that is so simple and yet is exactly what the song calls for (a playing style the Buck is particularly adept at). "Mythological Beauty" is another stunning song where Adrianne sings about her mother who had her a very young age, detailing her childhood including being rushed to the hospital while her mother held in arms covering her bloodied head with a rag. "Haley" contains a really cool guitar part, showing off Adiranne's great guitar skills (and a song I have yet to figure out how to play). The emotional climax is on the breathtaking track "Mary", a piano ballad that is just a true emotional gut punch and the standout for a lot of fans of this album. Big Thief has gone on to put out more truly incredible records, but somehow I always find myself coming back to this one.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/2hOYLjoRQFXcdviMiwtgxe?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Shark Smile, Mythological Beauty, Mary, Haley
