---
title: "My Favorite 40 Albums of 2018"
format:
  html:
    code-fold: true
---

This was a very significant year of change for me. I graduated from SUNY College of Environmental Science and Forestry in May 2018, and started my Ph.D in atmospheric sciences at the University of Albany a couple of weeks later. It seems fitting this was the year I decided switch up the format for the album of the list. If there was one year I could pick to redo a list for, it's probably this one. I decided on choosing 40 albums rather than 10 or 25 as there was just a ton of albums I really liked that year that I wanted to represent in some way. Look back now, I was right; there are just a ton of albums that I enjoy that year. However, 40 was probably a few too many as there are a handful of albums that haven't aged well for me. I would probably reshuffle the Top 10 pretty significantly as well. Albums like Low's hauntingly beautiful and experimental "Double Negative" or Beach House's subperb "7" probably deserve to be higher up on this list, while albums like Lucy Dacus's "Historian" or the fun hot mess that is Anderson.Paak's "Oxnard" probably should be lower on the list. Most regrettably, Pinegrove's "Skylight" is suspiciously missing from this list, which I still cannot believe I didn't include. Still, 2018 had a lot of music I really loved, and I often associate with graduation. It's hard not to look back at this list with nostalgia.

## My Favorite Songs of 2018

1.  Beach Life-In-Death - Car Seat Headrest
2.  Mither - Bill Ryder-Jones
3.  Rings - Pinegrove
4.  City Looks Pretty - Courtney Barnett
5.  Lemon Glow - Beach House
6.  Great No One - The Beths
7.  Almost Had to Start a Fight/In and Out of Patience - Parquet Courts
8.  To Be - Fox Warren
9.  Nevermine - Fourth Wanderers
10. 6 Summers - Anderson .Paak

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/5LG7vPzO2U3w453BfkxtR3?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 40. Miya Folick: Premonitions:

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/3nWDfV4stC2VQopcuHjJmO?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 39. The Greeting Cmmittee: This Is It

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/35H7mR1u6XET8YKvezYUkB?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 38. Saintsenca: Pillar of Na

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/62Q2VoAPpBo1OgfuJ63g6w?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 37. Earl Sweatshirt: Some Rap Songs

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/66at85wgO2pu5CccvqUF6i?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 36. Forth Wanderers: Forth Wanderers

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/3TZWID34tFQeznr09VILyt?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 35. Tash Sultana: Flow State

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/5eOlKFDAN9dXwYycRqEmnP?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 34. Optiganally Yours: O.Y. in Hi-Fi

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/41iCKFG0ZCapCuZKrxhcNb?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 33. Noname: Room 25

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/7oHM3Sj0l2nXAzGAxW0KOt?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 32. Dr. Dog: Critical Equation

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/0kafVzFVwhsAjOzA2h6QQB?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 31. Idles: Joy as an Act of Resistance

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/7BbRSUBwTB37ut0Ht3yAqt?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 30. Aqueduct Ensemble: Improvisations on an Apricot

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/6vSIDUOj0PG7gaCkYB3J2w?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 29. Wye Oak: The Louder I call, the Faster It Runs

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/3lSHd2sapKzXk7XkDac2zg?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 28. Sam Evian: You, Forever

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/7uOn3dpPMtthc9fx89AcPX?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 27. SPIRIT OF THE BEEHIVE: Hypnic Jerks

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/5l93RkfOpA9Whuziy038gB?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 26. Rubblebucket: Sun Machine

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/5Nzqg5Xb7xaKfl3XudeNiY?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 25. River Whyless: Kindness, A Rebel

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/1RNcYrqXqFyb3R6jjQrwT7?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 24. Pllush: Strangers to the Pain

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/2N9i29tj6fKP2XjVszMuvW?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 23. Let's Eat Grandma: I'm All Ears

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/5Bnhkya5cGltQFTrnC0grx?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 22. Gregory Alan Isakov: Evening Machines

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/5K7PZiOlAn8sxxhh0QTFuJ?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 21. shame: Songs of Praise

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/3A1kutvBmC6czSsSv7aR5E?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 20. Big Red Machine: Big Red Machine

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/3LBRCisCaxgQjb5nwSMPgU?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 19. The Milk Carton Kids: All the Things That I Did and All Things I Didn't Do

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/1BpQ1yTs26aKJg0aWqnzEq?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 18. Lawn: Blood on the Tracks

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/4NrrXVPLiggFGlvuOiUvw6?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 17. Unknown Mortal Orchestra: Sex and Food

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/7c2Xfq7aQKzs0KdSI3K7Rc?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 16. Haley Heynderickx: I Need to Start a Garden

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/4I8BEAiq1kPqRRlvWLTo5B?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 15. Snail Mail: Lush

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/2e48GqjEwCi87gQJanb1bf?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 14. Low: Double Negative

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/1zTkgOHx3mjrUvrhxq4osf?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 13. Saba: CARE FOR ME

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/6Te111t5gDZ7W94myHRqUt?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 12. Foxwarren: Foxwarren

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/27NP9XgsqFi9sfV9RZaqOa?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 11. Anderson.Paak: Oxnard

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/3rqqwtJE89WoWvMyPTvbZc?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 10. Mountain Man: Magic Ship

This is probably one of the most unique albums I've probably included on a top 10 list. This trio includes Amelia Meath of Slyvan Esso, Molly Sarlé, and Alexandra Sauser-Monnig of Daughter of the Swords, all who attended Bennington College together. Together, they produce a master class in minimalistic traditional and indie folk, opting for nothing more than simple acoustic guitar and their amazing vocal harmonies. Tracks like "Whale Song" and "Bright Morning Stars" use space perfectly to really necessitate their siren like vocal harmonies. The incredibly cozy and comforting, "Slow Wake Up Sunday Morning" is true highlight from this record, that is only made better in the context of the full album.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/26ahuw4JsKSGyNN1PCZe83?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Slow Wake Up Sunday Morning, Whale Song

## 9. Father John Misty: God's Favorite Customer

This is the follow-up record by one of the more polarizing figures in indie music; the similarly polarizing "Pure Comedy". I found ["Pure Comedy"](https://open.spotify.com/album/6nyf9D2M4je5BdNXwycoIe?si=726dvK63RDiqiNBTIuD3qQ) to be a very frustrating album, containing some of FJM's very best song writing, but often overshadowed by preachy and pretentious tracks (such as the exhausting 11 minutes track "Leaving LA"). "God's Favorite Customer" was a pleasant surprise for me, with FJM returning to the vulnerability and lush instrumentation that made 2015's ["I Love You, Honeybear"](https://open.spotify.com/album/4vTEFCLgDEgKIQXTrsmS6F?si=9mo0CwZET1ClafuRHulktg) so fantastic. This album can almost be viewed a somber sequel to I Love You Honeybear, being based around FJM being temporarily separated from his wife. There are some pretty dark moments on the record such as a literal self plea to not commit suicide on "Please Don't Die", or a metal breakdown in a hotel lobby on "Mr. Tillman". The true standout for me is the piano ballad "The Songwriter" which is about a emotional and sincere I've ever heard Josh Tillman sound. The track ends on the soul crushing line "what would it sound like if you were the songwriter, and loving me was your unsung masterpiece". A true return to form for Father John Misty.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/0hMPUtgjezv7gUsmhztvPv?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** The Songwriter, Mr. Tillman

## 8. Beach House: 7

Man, Beach House are just damn good at music. More impressively, their sound doesn't change dramatically from each record. And yet, they change just enough to keep things fresh and interesting, which has allowed them to create one of the most impressive catalogs in music today. On "7" (named for being their 7th album), they are at the height of their powers, creating their best work since "[Bloom](https://open.spotify.com/album/02PXepuNHYKvGnXYy03oCp?si=OTwCRMT_TjatzqikQrB8BQ)". The album opens with crashing drums on "Dark Spring", a change the largely electronic drum kit percussion on "[Depression Cherry](https://open.spotify.com/album/194CqC2Zi0kUFEPWedb3qr?si=ozOCfw9LTuaKJydiBJyPxw)", almost announcing how this album will be different. The transition from Dark Spring into "Pay No Mind" just sounds so cool as the synth drops right in. "Lemon Glow" is hands down one of the best tracks Beach House have ever created, with this ever-present ringing synth alarm, before heavily distorted guitars join the rest of the track. "Drunk in LA" is a really beautiful track, containing a really fantastic vocal performance from Victoria Legrand. Looking back, this album should have been quite a bit higher up this list, as it's a project I return to a fairly regular basis. Yet another magical dream-pop record from the band that does it the best.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/4qftBBO7pnYlek3mRENIvM?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Lemon Glow, Drunk in LA

## 7. Jeff Tweedy: Warm

As stated in other reviews, Jeff Tweedy is probably my favorite songwriter of all time, so anything he or Wilco release is probably going to be something that I enjoy. On "Warm", Jeff showcases some of the most vulnerable songwriting he's since the breathtaking [A Ghost is Born](https://open.spotify.com/album/1f8UM82zkRXTLy7qGp4lJF?si=h5zetrPCTCaLNRB491Iwaw). For instance, on the opening track "Bombs Above" regretting mistakes like "I should have done more, to stop the war, so I'm sorry". "Some Birds" is a Tweedy classic, with an ear wormy chorus and descending guitars that I think is about as good as anything he's done for Wilco in the past 10 or so years. In particular, I love the line "I break bricks my heart, but only a fool would call it heart". Perhaps the most earnest Jeff gets on this record is on "I Know What it's Like", where he wears his heart on his sleeve with lines like "Even when it's years away, I still think it's yesterday, I can't find the plot, something else is taking shape. I know it's a line when you say it's ok", pointing back to turbulent times in Jeff's life likely including is drug addiction. While this may not be as inventive as some of his previous works, this album contains a ton of really terrific indie-folk songwriting that really showcases Jeff's skill as a songwriter.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/2XTPulCL6EUx1thyJPnlmj?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Some Birds, I Know What It's Like

## 6. Lucy Dacus: Historian

Lucy Dacus's previous album "[No Burden](https://open.spotify.com/album/7lQ9R31OcTvMn2MojAuKVE?si=L4U6ZkVGTGWyubQlHkaUyg)" is a pretty charming indie rock album that contains a ton of potential. Here on "Historian", Lucy takes a big step in meeting that potential with a considerably bigger sound. Many of these tracks build to these amazing emotional climaxes, with the album being littered with some truly fantastic lead guitar parts. The album starts off really strongly with arguably her break out hit "Night Shift", the anthemic song about taking a night shift at job just to avoid an ex. All the extra instrumentation don't get bury Lucy's just lovely voice, with really great vocal performances on tracks like "The Shell" and "Historians". My truly favorite song on the album is the slow burn on "Timefighter", slowly building as Lucy and the lead guitar take turns raising the stakes on the track before the hammer is dropped on the back of the track. That song really kicks ass. The album's emotional climax is reach on "Pillar of Truth", a perfect B-side ballad to bring the album home (which contains probably the only time I'm aware of Lucy screaming". It's always really cool to an artist you like to try to mature their sound and largely pull it off. On Historian, Lucy Dacus has done just that.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/01GO03odsNlNLtvNETukWT?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Timefighter, Night Shift

## 5. Parquet Courts: Wide Awake!

You know 2018 was a good year for indie-rock when "Wide Awake" isn't my favorite. This album is just chock-full super jammy tracks with truly tasty baselines and perfectly messy lead vocals. For instance, the album opens with the energetic "Total Football" where the baseline is practically the melody of the track (and ends perfectly with the Andrew Savage screaming "Fuck Tom Brady!"). "Almost Had to Start A Fight/In and Out of Patience" just absolutely kick-ass, starting off as a messy punk song before transitioning into more energetic pop-punk. Immediately following it is the super fun "Freebird II" with another fantastic baseline and great sing along chorus. The album ends with super fun "Tenderness" with jangley guitars and bubbly piano. This album at times can be a tad preachy, but the bright yet gritty arrangements keep this album moving.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/5uTI2HcpAywDP8Vo1DpJta?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Almost Had to Start A Fight/In and Out of Patience, Total Football, Freebird II

## 4. Young Fathers: Cocoa Sugar

Young Fathers create such unique sound, fusing hip-hop, synth-pop, gospel, and electronica. Even more impressively, they manage to capture such joy and optimism throughout this record. "In My View" is perfect example (and the best track on the album), that has just this amazing sing-along chorus. The vocals towards the end starting off with "Lay my belly on a women, leave a damsel for Delilah" gives me goosebumps . Or on "Holy Ghost", another super catchy hook combined with a hypnotic flow on the verses. "Border Girl" is truly a wonder, containing such warm chorus with gospel choir backing vocals surrounding it. I truly love the vulnerability in the lead vocals towards the end of the song when things have reached their emotional climax. A thing about this record that really sticks out to me is the minimal use of snare drums (either digitally of from a drum set) in many of the tracks. At first it can make the songs feel a bit hollow, but on further listens, other components (particularly the bright melodies) of the tracks reveal themselves and more than make up for its absence. This, combined with the just top notch production, creates a truly a unique album that is a bit difficult to define easily. This is just a really freaking cool record and no artist sounds quite like Young Fathers.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/03Dp6OJS4wd7dI1rRszPwj?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** In My View, Holy Ghost, Border Girls

## 3. Bill Ryder-Jones: Yawn

Few know how to make a somber record quite like Bill Ryder-Jones. I first fell in love with Bill's music with his record [West Kirby County Primary](https://open.spotify.com/album/6Fdrnfx5pic8LlSGkmlVx9?si=NtY0X3-xSJW61z9yCmiZ2w), a wonderful album consisting of melancholy indie-rock tracks (Satellites is a true highlight with it's sludgy guitar coming in the beginning and end). On "Yawn", Bill Ryder-Jones keeps a similar aesthetic but fills out the guitar section and brings in a cello. The result is a beautiful tapestry of sound, with the rhythm guitars, cello, and Bill's soft-spoken voice laying a foundation for the bright lead guitar to drive the melody. The album opens with "There's Something on Your Mind", showcasing a very similar sound to West Kirby County Primary, before arriving to the sound of the rest of the of the album. "And Then There's You" is probably the brightest the album gets, containing a pretty badass guitar lick. "Don't Be Scared, I Love You" is unexpected earworm, bolstered by the low hum of the cello and plucked strings played at the top of the neck of an electric guitar. But the true standout is the masterpiece that is "Mither" (a word I had look up meaning to make an unnecessary fuss, moan, bother). To this day, I'm still in love with track as it's just so easy to get lost in. A slow-burn kind of song, with Bill opening with "Will you still play on mind?" . But the song evolves on the second part, bursting into a sea of fuzzy guitars, with the lead guitar popping in and out of the song. This album is a perfect kind of winter or late-night record, when you're feeling a little bit down. Truly a breathtaking effort from Bill.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/70I1oXkFprQzZ2DJAchR7K?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Mither, Don't Be Scared, I Love You, And Then There's You, There's Something on Your Mind

## 2. Car Seat Headrest: Twin Fantasy

I debated about including this album on the list. On the one hand, this album is a re-recording of the [2011 version](https://open.spotify.com/album/5aqXdOgdhpSfYcCde4SHgI?si=OuYNV9ikS52kMFZCo5PtKg) so does it really count as a 2018 album? On the other hand, many of the arrangements sound very different (the album sounds like it was recorded on a potato) and I was only familiar with the 2018 version. Then I realized that this is my list, and this album rules, so I can include it if I want. As mentioned, Will Toledo released the 2011 version to Bandcamp when he was only 17 years old, which looking at the scope of the album is a truly remarkable thing. This re-recording is welcomed as while the original version contains a lot of charm, the production value makes it a difficult listen (unless you really love your lo-fi). There is so much ambitious and power to so many of these tracks. Take the opening track. "My Boy - Twin Fantasy", a simple but effective introduction just inundated with power chords and belting vocals. Then there is the true masterpiece (and my top song of 2018) that is "Beach Life-In-Death", a sprawling 12+ minute track split into three sections. There are a lot of great lyrics in this song but the line "they should call it anti-depression, as a friend of mine suggested. Cause it's not the sadness that hurts you, it's the brains reaction against it" is one that has stayed with me. The front half of the album is truly stacked, with album quickly transitioning to 4 amazing singles started off by "Sober to Death", a great indie rock track that ends with these really cool triplets with the refrain "Don't worry, you and me will never be alone". "Bodys" super danaceble track which is amazing to see live. "Cute Thing" is just an absolute banger, with guitars on the back that just rip so hard. I particularly enjoy how this album closes: A 16 minutes oddessy on "Famous Prophets" (another track that rips pretty hard, and great conclusion on 'Twin Fantasy (Those Boys)". It's staggering to see that a 17 year old had the ability to craft such a powerful album. This (along with other work) solidified Will Toledo as a Bandcamp hero, gaining a pretty strong cult following throughout the 2010s that only grew rapidly after the release of the classic"[Teens of Style](https://open.spotify.com/album/3KpYyDP8q8sUBxatHaYEsP?si=YTP3nYmnQCCT3PLzVfnUTw)". Safe to say, Car Seat Headrest is a favorite of mine, and I get the feeling this project has another classic under its sleeve.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/20U1UWeGcGq7JVW0tf8yfH?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Beach Life-in-Death, Cute Thing, Bodys, Sober to Death

## 1. Courtney Barnett: Tell Me How You Really Feel

There was no album in 2018 that I was anticipating more than the follow up to Courtney Barnett's incredible debut ["Sometime I Sit and Think, and Somtimes I just Sit"](https://open.spotify.com/album/7Lnfvco5xEeqoqwZdRhGJb?si=-tk881GYScidan_veRBPLw), and "Tell Me How You Really Feel" was everything I needed it to be. Compared to the more observational approach on her previous effort, Courtney takes a slightly more serious tone, tackling issues from mental health to sexual assault. The most impressive thing to this record is just how consistent it is. There isn't a dud or mediocre track in the bunch. The album opens strongly with "Hopelessness", a reserved track with some Courtney's most introspective lyrical work like "Your vulnerability, stronger than it seems. You know it's ok to have a bad day", before erupting into a fuzzy guitar haze. Things transition quickly to my personal favorite on the album "City Looks Pretty", as Courtney points out benefits of anonymity in a city when your mental health isn't at its best, with lines like "Friends treat you like a stranger and strangers treat you like their best friend oh well". The song excellently with a tempo change into a simple but bright blues riff. Mental health is a clear theme explored throughout the album, like on "Need A Little Time" with lines like "shave your head to see how it feels. Emotionally its not that different, but to the hand it's beautiful". This is a line that I still have a hard time interpreting beyond a haircut can provide someone small sense of control and that is comfortable. The album at this point really picks up the pace, with the iconic lead single "Nameless, Faceless". Courtney laments the general lack of safety that can be associated with being a woman, whether it's wanting to walk alone in the park at night without need to have your keys between someone's fingers, or dealing with targeted online harassment (sidenote, this song has such a funny line with"I could a bowl of alphabet soup and spit better words than you"). At this point, the album devolves a bit, with anger clearly being released on the kick ass "I'm Not Your Mother, I'm Not Your Bitch". Still, even in the anger, Courtney manages to keep her sense of humor with lines like "I'm not your mother, I'm not your bitch. Di..Did I stutter? A little bit". Recognizing some of the heavier material on this album, Courtney closes the album with the delightful "Sunday Roast", a welcoming song describing a brief escape from the world with a simple dinner with a friend. The final track leaves the listener with a small sense of optimism, that even in a dark and frustrating world, simple moments like dinner with a friend can be life affirming. 2018 was tremendous year for indie-rock, (evidenced by 4 ending up in the top 10), so it should be no surpise that an indie-rock album topped the list. For this year, Tell Me How You Really Feel is the best of the best.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/3l7JWewI3ZByxaT5BCgRx2?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** City Looks Pretty, Nameless Faceless, Need a Little Time, Hopefulessness
