---
title: "My Favorite Albums of 2022"
editor: visual
format: 
  html: 
    code-fold: true
website:
  comments:
    hypothesis:
    theme: clean
    openSidebar: false
---

I gotta admit, 2022 was pretty darn good to me. I began the year by successfully passing my oral exam, which is the final step before I defend my dissertation and (hopefully) receive my PhD (hoping to be done in 2024, which isn't far away....). I also met my lovely girlfriend Karen, who has been a wonderful addition to my life. World events have been somewhat positive as well. The war in Ukraine has been going considerably better than anyone (besides Ukraine) could have imagined. COVID is starting to become a more mild and losing it's ability to collapse the health care system. Perhaps the biggest develop in my field was the passage of the inflation reduction act, which is mostly a giant climate bill throw \$350+ billion dollars in various ways at tackling greenhouse gas emissions in various ways, which has given me more hope that U.S. is actually going to do something about climate change.

On top of all of the relatively positive news this year, 2022 was a truly incredible year of music. I have never had so much trouble deciding on my list this year, with 11 albums that probably would have made the top 25 albums any other year that didn't make this year. Artists I had to leave off have made other lists in the past including Wilco, Nick Hakim, Andrew Bird and Alt-J. The top 10 is arguably the strongest I've made, with the top 4 positions only being decided a week or so before posted my list. Lastly, my favorite album from this year is the front runner for album of the decade and one I come back to constantly. All in all, it's been a pretty good year for me.

## My Favorite Songs of 2022

1.  The Place Where He Inserted the Blade - Black Country New Road
2.  High Hopes - Sweet Pill
3.  Gold Chain Punk (whogonbeatmyass) - Soul Glo
4.  Sugar/Tzu - Black Midi
5.  Expert in a Dying Field - The Beths
6.  All the Good Times - Angel Olsen
7.  Basketball Shoes - Black Country New Road
8.  God Turn Me Into A Flower - Weyes Blood
9.  Summer Dream - Bonny Lighthorseman
10. Satan - Andy Shauf

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/4FHnWCczoYevM2M6DTdV2v?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## Honorable Mention: Voice Actor: Sent from My Telephone

Before I get into that ranked list, I wanted to highlight the craziest album that I found this year, the experimental electronic piece "Sent From My Telephone". This album contains a whopping **109!** tracks and a run time of 3.5 hours. It's a collection of spoken word, ambient music, industrial music, and occasionally singer songwriter and folk compositions. This album is pure chaos, with little structure track to track. In fact, the tracklist is in alphabetical order, implying that the artist is fine with people putting the album on shuffle. I highly recommend doing this as it gives you a unique listening experience each time. I'm still trying to fully wrap my head around this album, but I've fallen in love with it and will be on the look out for albums like in for next year. The reason I put this as an honorable mention, as it really doesn't feel like an album that I can compare to others, but I wanted to point it out at the same time. It's a pretty daugting task, approaching a 3.5 hour album, so some tracks to try first probably would include "Carefully", "Battling Dust" and "Badman". I suspect most people won't be into this, but I still hope you'll give it a try, as it's the craziest thing album I've added to a end of year list.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/4h9EUsDMvwsUdmXEvK449j?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Carefully, Battling Dust, Hide, Office, Badman, and many more

## 25. Pinegrove: 11:11

Jussssst sneaking into the top 25 list is my beloved Pinegrove. Pinegrove in recent years have become very environmentally conscience and wanted to make an album dealing with the anxieties of catostrophic climate change. Here, they settle for simpler arrangements to allow Evan Stephens lyrics to be front and center. The album opens with the best track "Habitat" starting with loud guitars, before the song deconstructs into the beautiful acoustic section complete with nature sounds in the background, before transitioning in the urgent "Alaska". "Orange", a song the placed very high on my top songs of 2021, returns for 11:11 and remains as necessary as ever. My only minor gripe with this album is how little of the rest of the very talented band we get to see on this record. Still, Pinegrove have made yet another terrific record and a solid addition tho their catalog.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/6sOmBkyGWJpzR04C7U7BZE?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Habitat, Alaska

## 24. Danger Mouse and Black Thought - Cheat Codes

The only hip hop album to make the top 25, is the MC Black Thought teaming up with the legendary producer, Danger Mouse. Together, they create this tapestry of soul and jazz rap tracks with tons of fun features across the record (including a posthumous feature from MF DOOM). I love the piano part that opens "The Darkest Part" before the beat comes in full force, with Black Thought and Raekwon as they paint a bleak picture of the current state of music and how its affecting artists. "Because" has great features from Joey Bada\$\$, Russ, and Dylan Cartridge, as the discuss the horrible state of poverty in the U.S. Tons of incredibly lyrical work throughout, backed up by top notch production from a legend.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/0rEbmIQjHTKzKraH4UqiDy?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Because**,**The Darkest Part

## 23. Bonny Light Horseman: Rolling Golden Holy

It's fun to see a super group return with a follow-up record. Bonny Light Horseman have a great ability to make these cozy indie-folk songs that bring so much comfort. "Exile" starts the album beautifully with a acoustic guitar and banjo as Eric D. Johnson, and Anais Mitchell intertwine their voices. But the real highlight is the remarkable "Summer Dream". The hollow bodies guitar and Anais's peaceful vocals just just lull me into a dream like state. This album is a perfect companion for those cold fall or winter days where you dress up in your warmest clothes.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/43mr98g3RoWlC3jyxAKf5I?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Summer Dream, Exile

## 22. Petrol Girls: Baby

Completely opposite from the above record, Petrol Girls come in with some real punk shit. True to the genre, Petrol Girls don't pull any punches as they scream about issues ranging from misogyny, racism, and police brutality. "Feed My Fire" is a face melter with a crazy drum line on the chorus. On the not subtle but effective "Baby I Got An Abortion" acting as a tongue in cheek celebration of getting an abortion. "Violent By Design" has this great vocal performance that feels like speech as much as singing. This is a must for any punk fan out there.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/3QUnWPhBPq5FRG3H2gcPat?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Feed My Fire, Violent By Design

## 21. Spoon: Lucifer on the Sofa

It's super cool that Spoon is still able to put out damn good music in 2022 while largely sticking to their traditional sound. The crunchy guitars throughout this record is a real highlight for me,driving the songs forward. "Held" is a fantastic opening track, that has this super cool bassline that starts as frantically playing one note before stumbling into formation for the song. "The Hardest Cut" is certainly the best song on the album, with a busy little guitar riff and handclaps before the explosive chorus sung by raspy Britt Daniel. They describe the album as "the sound of classic rock as written by a guy who never did get Eric Clapton" and I'm not sure I can write anything better than that.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/1szMY4QqnQZgNuyLBC4jUQ?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** The Hardest Cut, Held

## 20 Harry Styles: Harry's House

Harry had been on my radar for a while at this point as an pop artist with more substance than just being from a boy band, and he absolutely delivers here. This album just contains so many alt-pop gems that are fit for any summer soundtrack. Like other pop artists I'm loving in this day in age, there is a subtlety to the way he approaches his songs both in writing and vocal performances. "Grapejuice" has this great ringing guitar note throughout the track combined with banging piano chords that pair perfectly with his revered vocals that create a relaxed vibe. "Keep Driving" has this great dreamy aesthetic to it that makes you want to get lost on a road trip with someone you love. Finally, Matilida has this amazing acoustic guitar part that to this day still eludes me, despite my best efforts to learn it. This is furhter evidence to me that pop music is in a really great place.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/5r36AJ6VOJtp00oxSkBZ5h?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Grapejuice, Matilda

## 19. Sweet Pill: Where the Heart Is

The best emo rock album you'll find in 2022, and probably in a while. This is just a really tight and talented band capable of making these really catchy and emotional tracks. The title track is a perfect way to start the album, with the lead guitarist dancing all over the neck of the guitar with and incredibly busy drum line. But the real standout is the lead vocalist, Zayna Youssef, who is the absolute perfect frontwoman for this band, bringing so much charisma to each every song. In particular, her vocals on "High Hopes" is extraordinary, brimming personality and swagger. Hands down my favorite vocal performance of the year, and just missed out on being my favorite song. Looking forward to more from the really talented band.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/1SmAUgSjmVihnEuTZoALSO?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** High Hopes, Where the Heart Is

## 18. Alvvays: Blue Rev

The long awaited return of the beloved indie-darlings, Alvvays. On "Blue Rev", they take a step back from their indie-pop sounds showcased on the fantastic [Antisocialites](https://open.spotify.com/album/2Yy84EeclNVwFDem6yIB2s?si=qSuiNN_7SSO6rQer5czxlA), going for more a more shoegazzing, noise rock kind of sound. But, they keep the thing they makes them a special band; the ability to craft anthems (classics like [Archie, Marry Me](https://open.spotify.com/track/0KVWVuutF9Dn8li4HdyAeU?si=abdf63a1c7a645a9) and [In Undertow](https://open.spotify.com/track/6Px7VvXLTjMP6J2nTQ6bIh?si=d65c70b697634f32)). "Easy on Your Own" is a perfect example of this, as it builds to big emotional climax that I imagine would be amazing to see live. Most of the album contains songs with pretty quick tempos, which makes feel like its in a rush and ends before know it. This make it easy to listen to over and over. "Belinda Says" is my personal favorite; another anthem that has such incredible key change towards the back of the song. Truly an amazing effort from Alvvays and well worth the wait.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/1dShPPoxXfzbjFO1jIHJZz?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Belinda Says, Easy On Your Own?

## 17. Toro y Moi: MAHAL

I'm not sure there is an album with better vibes than Toro Y Moi's most recent record. I have been a fan of his for many years at this point, but never found more than one or two songs from his records that I liked. MAHAL has broken that trend and then some. This album is just filled with psychedelic rock and r&b tracks that bleed into each other wondefully. The album starts off boldly, with a guitar features from the super talented Unknown Mortal Orchestra on "The Medium" before going into the saxophone ladened "Goes By So Fast". "The Loop" is a song I dare anyone not to bop their head to, as laments getting stuck in a boring routine that is making time pass too fast. The album closes strongly with "Day's in Love" that almost feels like something out a 70s rock. Far and away my favorite project from Toro y Moi.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/16AQyjz1z9rOsTm6iVrBUR?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** The Loop, Days in Love

## 16. Barrie: Barbara

After a really great debut record "[Happy to Be Here](https://open.spotify.com/album/6t1OiiVq9VIbW1SUHaXX7W?si=B8sPUqMcTcipqjT_rM5QgQ)", Barrie are back with an even more impressive collection of indie and alt-pop tracks. The album starts of really strong with bubbly yet melancholy "Jersey" as Barrie refrains "don't wanna give it up yet". "Frankie" is this amazing synth-pop track record that manages to do some many things in the chorus, with disjointed drums and ringing digital production sounds in the background. This album took all the strengths of their previous record and built on them, creating a really enjoyable sugar-sweet indie pop record.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/5eieb3BvJUgPIzE5VkdyWL?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Frankie, Jersey

## 15. Soccer Mommy: Sometimes, Forever

Soccer Mommy has been a really good songwriter for a long time now, finding ways to modernize the angsty-rock nostalgia of the early 2000s. On "Sometimes, Forever", she takes a huge leap forward creatively, keeping the bones of those 2000s-eqsue songs but adding grudge and underground music experimentation. The album opens with "Bones", which is not wildly distinct from her previous work before it transitions into the grunge heavy"With U", with thick distorted guitars and muted verses. The lead single "Shotgun" is probably the best track on the record, finding the perfect balance between her ear-wormy songwriting style and this new found grudge style. She closes with "Still", another track reminiscent of her older work that just feels so fitting to end the album with. It's always great to seen an artist pull off a new sound, and Soccer Mommy has done just that.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/3VXLdJpzeaAyX9Tbm0i0zn?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Shotgun, With U

## 14. Klangstof: Godspeed to the Freaks

In 2016, Klangstof released one my favorite albums of that year and the decade, [Close Your Eyes To Exit](https://open.spotify.com/album/314g2JtzkHhPw8uo6lrAwz?si=gggKkACsRdezDp6oCIwLMA). which married indie-rock and electronic elements to creating the dream-like aura across the songs. "Godspeed to the Freaks" is continuation of this sound, with an album more consistent but also more somber across the tracklist. There is this ominous feeling that surrounds the album, driven by the melancholy piano and hushed vocals from Koen van de Wardt. Still, there are bright spots on the record, like "Plastic Gun", which has synth and bass lines that goes pretty hard, or the ringing chorus on "Disguiser". I love how the album closes, with "Syliva", a slow burn track with a sing-along chorus that serves a perfect conclusion for the indie-pop adventure this album takes you on. I still haven't found a band that creates a similar somber-pop sound similar to Klangstof, which really points to the unique approach this band to takes to music.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/2nTU8TNHOrWAw4B7tgYHbJ?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Plastic Gun, Disguiser

## 13. PUP: The Unraveling of PUPTHEBAND

PUP continues their reign as the best pop punk band in music right now (sorry Paramore...). Compared to their instant classic "[Morbid Stuff](https://open.spotify.com/album/504XSXhUJlzztcMV4YMaDV?si=lBxuDr50RkihtYeM-v0rqw)", which contained straight ahead pop-punk and emo-rock sounds, PUPTHEBAND goes for a nosier, less polished sound, particularly towards the back of the album. As the album evolves, the tracks become less melodic and become more chaotic, more than likely symbolizing the bands inevitable unraveling. I find the piano skits/interludes endlessly entertaining, as the band is running out of money trying to finish a record and fighting. "Totally Fine" is such a great way to start the record, starting off chaotic before settling back into the farmilar melodic choruses of their previous work. "Matilda" is another highlight of the record, containing the perfect chorus to scream-sing to (and which I did in person in the at a show in the summer of 2022). As someone who grew up on Green Day, pop-punk is always going to have a special place in my heart. PUP is doing it the best right now, so I guess the take the most up the most room.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/2bRpK0BpzYUQZYIzri35n6?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Totally Fine, Matilda

## 12. Alex G: God Save the Animals

I'm still trying to figure out how to define the sound of Alex G, since he combines so many different things in his music. One thing I know for sure, is that he is one of the most consistent songwriters in music right now. His previous record "[House of Sugar](https://open.spotify.com/album/2kCDZ3gCr5hXFgbFsPMcxP?si=alO62pFLTfe-KM8JRxSSJA)" is indie-folk gem and was my second favorite record of 2019 (a pretty stacked year). On "God Save The Animals", I still haven't figured out exactly why I love this album so much. On paper, much of it seems like simple indie folk songs you've heard a lot times. But I don't know, there is just something special going on in the background. "Runner" has the infectious melody to it, with a piano bringing the song to life. I also love how he says "they hit you with a rolled up magazine". Even with the deceiving songwriting approach to this record, Alex finds ways to bring back his famous experimental songs that just about every album has like on "S.D.O.S" and "Blessing". "Miracles" is another beautiful track that just brings me so much comfort, with Alex's fragile vocal performance and the fiddle in the background. My best guess to what makes this album click with me is that Alex G, despite all of production tricks he brings to music, there is core sincerity to everything he does and God save the Animals has boatloads of it. This yet another special addition to Alex's stellar catalog.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/6TzgWk5HZItbFmMT7hH4bU?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Runner, Miracles

## 11. Soul Glo: Dispora Problems

Man was I bummed to leave this off my top 10 list, but it was such a competitive year. No matter, let me tell you that THIS ALBUM FUCKING RIPS. It's such a fresh sound, combing screamo and punk with trap rap, giving this incredible speed and volume not only in the instrumentation but from the flow of GG Guerra. The album starts with a bong rip to the 20th Century Fox drum roll before the guitars start in on "Gold Chain Punk". The song starts off fairly bright before getting more and more chaotic and by the end you can't ever recognize where you came from. There is tons of anxiety in the lyrics (if you can keep up) that make the song so much more real. The band is also incredibly talented, constantly changing tempo and the approches to their sound, which keeps the album feeling fresh. "Jump!! (Or Get Jumped!!!)(by the future)" is an absolute whirlwind of a track that changes tempo so many times you get whiplash. "Driponomics" is such a mood change for the record, moving to truly insane beat instead where GG gets to really show off his flow (and super cool feature from Mother Maryrose). I'll also love any song that comes after Reganomics. This album is so unique in its approach and just hits so go damn hard. Not sure there is a more thrilling album than this released in 2022.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/2ZYhM0LXHZ38te98EizcQW?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Gold Chain Punk (whogonbeatmyass), Driponomics, Jump!! (Or Get Jumped!!!)(by the future)

## 10. The Beths: Expert in a Dying Field

The Beths are becoming a force in indie-rock. Their first two albums are full of sugar sweet power-pop songs that just feel so good. On "Expert in A Dying Field", they have truly outdone themselves here with the catchiest tracklist yet. Everything about this album is just so charming and infectious, whether is the sweet vocals from Elizabeth Stokes or the clear chemistry this band has with one another. The title track is such a well crafted song, starting off fairly reserved, before building to the end with their classic call and response harmonies between Elizabeth and the whole band. This call and response is utilized throughout the album and I love it every single time because it just adds so much personality. "Silence is Golden" is neat little musical experiment for the group with rapid lyrics from Elizabeth and drum beat that I can only imagine is really difficult to keep on tempo. "Head in The Clouds" is another fantastic track that has the band almost serve as doo wop group with their back up vocals. It's amazing to me that after all of the indie-rock music that has been released in the past 20 years or so, there is still life in the genre. Bands like The Beths are the exact reason why I keep coming back to it.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/6RWLJx7kQLSnwwPyTqPj0U?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Expert in A Dying Field, Head in the Clouds, Silence is Golden

## 9. Weyes Blood: And in The Darkness, Hearts Aglow

Yet another stunner from Weyes Blood. Weyes Blood blew up with her tremendous album "[Titanic Rising](https://open.spotify.com/album/0Cuqhgy8vm96JEkBY3polk?si=jxs2b2xpRKmAYF2MTY-hZw)", combining psychedelic production techniques with 70s singer songwriter vibes and the results are breathtaking. Here on "And in The Darkness, Hearts Aglow", the second album of a triology, she takes a step back from some (but no all) of the production, making the songs feel a bit more organic. "It's Not Just Me, It's Everybody" is content to swim it's own aesthetic, letting Natalie Mering's voice carry you through the song. A real highlight is"Children of the Empire" , an expansive track with strings, drums, bells, harmonies, and some pretty great snapping. But the real show stopper for me is "God Turn Me Into A Flower", a patient track containing just synth lines and a truly incredible vocal performance from Natalie. The outro to the track has this great ambient section that works nature songs into that is really stunning. "A Given Thing" is a perfect way to close the record, a piano ballad to close proceedings with another stunning vocal performance from Natalie. This album doesn't have the same studio tricks as her previous album, but I feel like this album does a better job showcasing what a truly incredible singer Natalie Mering is. The only thing left to say is I cannot wait for the final album in the trilogy.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/artist/3Uqu1mEdkUJxPe7s31n1M9?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** God Turn Me Into A Flower, Children of the Empire, A Given Thing

## 8. Jockstrap: I Love You Jennifer B

In September, I was looking one more kinda experimental record to add to my top 10 list. Enter the duo of Georgia Ellery (also a member of Black Country, New Road crazily enough) and Taylor Skye, under the name "Jockstrap". "I Love You Jennifer B" is this incredibly collection of glitch pop and electronic songs that keep you guessing throughout the record. The album opens pretty unassuming with "Neon" before it explodes in a rush of guitars and keyboards out of nowhere. There is so much cool production on the vocal performances from Georgia, like on "Angst", speeding up the track, which feels almost unsettling. "The Greatest Hits" is a real highlight for, with a such a catchy beat and keyboard part that I always bop my head along to. But my personal favorite is on "What's it All About", this dreamy track with strummed acoustic guitar and string flourishes that make for a really beautiful song. There so many other tracks with crazy production that I really don't have time to get into detail with like "Concrete Over Water" or "Glasgow". Please spend time with this album, you've never heard anything quite like it.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/4YFlC5Abaj48ERwaOPfpu8?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** What's It All About, Greatest Hits, Concrete Over Water

## 7. Florist: Florist

I first discovered Florist with their 2017 record "[If Blue Could Be Happiness](https://open.spotify.com/album/6Urg55LAGNL5QKM0bz8g2v?si=IFc3kvsTT3-xVDsDdDtY-A)" and fell in love with the title track. They just create these spacious songs that are so peaceful that sound like something that could come out of Adventure Time (particularly the end credits song). On their self titled record, they build on this by creating a minimulaistic indie-folk record that borders on ambient at times. Throughout, there are these great little production parts that add so much to such bare bone songs. The lead vocals are perfect for this album, matching the peaceful songwriting approach. This is a pretty long album, with 19 tracks coming in a just short of 1 hour makes it difficult to handpick tracks, but "Sci-Fi Silence" and "Two Way"s are tracks that really stand out to me. I really enjoy the ambient tracks throughout the record that include bells, rain, and subtle guitars (like on "Duet for Guitar and Rain"). They also serve to help prevent the record for dragging on or overstaying its welcome. This album even has a minimalistic jam on the track "43", which has the great guitar solo towards the end of it. This album is such a perfect way to declutter my brain, particularly on stressful days at work or as I'm falling asleep. Florist have really outdone themselves with this work.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/7EvfFPMMvMJ20olfdEkPBR?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** 43, Two Ways, Sci-Fi Silence.

## 6. Beach House: Once Twice Melody

Normally, I'm not a particularly big fan of double albums, as in attempt to fill out the tracklist, artists sometime include weaker songs that could have been removed for a tighter single album. But it seems 2022 was a major exception to that rule, and I can't be surprised that the dream pop masters were the ones to do it. The release of this album may have help in part with it, as they released it 4-5 songs at a time, which helped the audience digest the individual tracks more easily. What can I say, its another Beach House triumph. The self title track is a perfect way to open the album, with plucky acoustic guitars, lush strings, and Victoria's ethreal vocals. "Pink Funeral" is one of my favorite tracks they've ever release, sounding a bit more sinister compared to their other work. This album contains so many songs that will likely become classic Beach House tracks, like "New Romance", this big sounding track that feels so optimistic, especially as the chorus kicks in with the drum kit. "The Bells" has this fantastic ringing guitar to that I'm obsessed with. This album can feel a little bit daunting going into it, so approaching it the same way Beach House released the tracks is honestly a great way to become familiar with. Large tracklists can sometimes cause people to ignore certain songs. But on this record, just about every song requires your attention. Beach House remains the king and queen of dream pop.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/79NySyjxJ8xric31mXKMAo?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Pink Funeral, New Romance, Once Twice Melody

## 5. Angel Olsen: Big Time

It's becoming kind of absurd how much incredible music Angel Olsen has released, and Big Time is yet another incredible addition. The origins of the album are unfortunately tragic, as Angel had just came out gay to her parents and was greeted by love and acceptance, only for her to lose both of them suddenly a couple of weeks later. Really changes of the context of many of the songs. Angel had humorously billed this album as "not country, but it's also not not country" which I think a perfect description. Tracks like "This is How It Works" and the title track, you can clearly hear country influences, particularly with the very prominent and well done pedal steel. Angel is still capable of creating a huge ballad with the opening track (and best track) "All the Good Times". The line "the way that she said, as heavy as led, you know how to get straight to my head" gives me chills on every listen. "Ghost On" is another great ballad that flows so beautifully before the great guitar solo comes in towards the end of the album. As with any Angel Olsen record, her iconic vocals shine through on just about every track, which elevates already great songwriting to another level. The final track "Chasing the Sun" is an emotional ending to the album as Angel surrenders to the love she has found. I'm getting to the point of running out of superlatives for Angel. All I can say is give this record many listens.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/02R7PREL8nCr02CEYLy7YH?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** All The Good Times, Big Time, Ghost On

## 4. Black Midi: Hellfire

I was always on the cusp of really liking Black Midi but there was always something about their music that was just a touch too inaccessible for me. They always had cool experimental jazz and rock ideas but I just could never quite get into it. On "Hellfire" they manage to find the perfect balance between their wild experimental art rock with some truly beautiful moments of jazz. The album opens with the title track, which feels like an introduction to what you'll hear on the record as it transitions into the masterpiece that is "Sugar/Tzu". The track opens with a boxing announcer getting you ready for the craziness that is about to ensue. The song the sprints into outrageous arpeggios and jazz played a rapid pace. The song ends with horns erupting and some unbelievable drums lines. It then cleanly transitions in the equally crazy "Eat Men Eat". Its baffling how many musical ideas this band manages to fit into a pretty short album (39 minutes in total) without ever feeling unfocused or forced. "The Race is About to Begin" is case study in this, shifting in and out of crazy guitar riffs and unhinged vocal deliveries, before settling into something akin to a lullaby. "Still" is among the sweeter moments on the record with some wonderful acoustic guitar, especially around the 2 minute mark. "Dangerous Liaisons" plays almost like a jazz standard, with gorgeous horn sections and piano, which would feel almost out of place on the record if wasn't Black Midi playing. This is one of the most ambitious records released in 2022 and they really just nail it. It's a record that a lot of people man not get into right away, but there is some many cool things going on, its absolutely worth spending time with.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/68z6MWYYNmvTcru1QMcYId?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Sugar/Tzu, The Race is About to Begin, Still

## 3. Ethel Cain: Preacher's Daughter

Trigger warning for some pretty heavy stuff on this record. My first impressions when this record came out were fairly positive. It was a slowburn kind of record with some cool studio production and pretty distinctive vocalist in Hayden Silas Anhedönia. But there was just an extraordinary buzz in the online music communities I'm involved with that I just wasn't seen. As I was relistening to this record as I was getting ready to start my list, I decided to do a little more research on the album and really study the lyrics. I was shocked at what I found. For starters, I didn't recognize this was considered a [slowcore](https://en.wikipedia.org/wiki/Slowcore) record, which allowed me to approach the record from another angle. But the real change was learning about the story within the album. This story follows Ethel, a daughter of preacher in rural southern town. "American Teenager" serves a character development, exploring Ethel's desire to leave her hometown in search of something more, trying to heal from the end of a relationship. The album only gets more somber from here, on "House in Nebraska", dealing with the crushing loneliness of her love abandoning her in the very same town she wants out of. She does eventually leave but ends up with a incredibly toxic and violent man on "Western Nights", who eventually dies at the hands of the police during a bank robbery. The A side closes on "Family Tree", as Ethel explores the likely sexual assault from her father and the complicated feelings between her hatred for him and yet unable to not love him anyway. You think Ethel as finally found true love in "Thoroughfare" as she travels to California with a kind stranger named Isiah, before falling in love with him. But the rug is ripped from under the listener, as Ethel is drugged up and pimped out on "Gibson Girl". She begins to hallucinate on the dark, industrial song "Ptolemaea" as confronts the demons before her. Ethel screaming "Stop" is gives me chills every time I hear. On "August Underground" Ethel attempts to escape from Isaiah but to no avail, and is eventually killed by his hands, represented by the piano interlude "Televangelism" representing her ascent to heaven. Ethel on the closing two tracks comes terms with her death, worrying about her mother never learning about what happened to her, as Isaiah cannibalizes her body (yes you read that right). I don't know if I've ever had an album give such visceral reaction before. The terror that Ethel faces just leaves a pit in my stomach. I wouldn't say this album is "enjoyable" (though it is beautiful). But it's a true work of art that I think won't be matched for a while. It's a tough listen, but one worth going through.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/3WmujGwOS0ANHkJRnMH6n8?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Ptolemaea, Strangers, Televangelism, Hard Times

## 2. Big Thief: Dragon New Warm Mountain I Believe You

This is probably a good album to listen to after the Ethel Cain record..... I'm running out of words to describe what an amazing band Big Thief is. They just continue to release incredible record after incredible record. I've heard a lot people get excited that Big Thief released a country album, but honestly does this is a disservice. They cover all kinds of ground in the indie-folk and singer songwriter realm, from traditional Americana, to more experimental indie-folk, blue grass and more. I think the best comparison is maybe The Beatles's "[The White Album](https://open.spotify.com/album/1klALx0u4AavZNEvC4LrTL?si=cxACRYzCRHeqj-8dOilWLg)", but only in the sense of the long tracklist with its sprawling sounds. The album opens sweetly, with the simple indie-folk song "Change" that has this delightful guitar solo from their lead guitarist, Buck Meek. In then transitions into the frantic "Time Escaping", with a cacophony of sounds. "Spud Infinity" is this great blue grass song, complete a jaw harp (which required the funniest google search to figure out what the hell it was called). The album then goes into my favorite on the album "Certainty". Its such a simple little song, but its so playful, and I just adore Adrianne Lenker'ss vocal performance on it and the lose harmonies from Buck. Big Thief produce such a crazy sound on "Little Things" with echo acoustic guitars layered by one of my favorite ever guitar performances from Buck. There doesn't seem to be a ton of song structure to it, but it just works so well. It then transitions perfectly into the criminally brief "Heavy Bend", with it's plucky guitar and crisp drumbeat. I've talked about a lot of songs already and I'm not even halfway through the tracklist which just shows how much incredibly good music is on this album. The second half opens with amazing bluegrass tune "Red Moon" where Adrianne really leans into the twang in her vocal delivery. "No Reason" is another favorite of my, with the stunning flute solo on the bridge of the song and the lovely camrodory of the band as they together sing "come together". "12,000" lines isa peaceful folk tune with fantastic vocal performance from Adrianne. Then there is "Simulation Swarm", a catchy indie-folk tune that has this intrigue and mystery to it, as crescendos and backs off throughout the song, and feels like its destined to become a fan favorite. The album closes with one more country track, "Blue Lightning" with great messy lead guitars from Buck again, acting a perfect way to bring all of this together. This record has 20 songs and runs from 1 hour and 20 minutes. And yet, it doesn't drag even a little bit. There is such comfort to how Big Thief approach this work. Its peaceful, playful, friendly, and above all, amazing executed. I dare say this is their best work yet and album that I will come back to time and time again.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/7Ln81p86r5cCsesd3KBWIY?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Certainty, Reasons, Simulation Swarm, Little Things

## 1. Black Country New Road: Ants from Up There

It was going to take something pretty damn special to beat Big Thief's latest release; Black Country, New Road have done just that. It's honestly pretty hard to describe how much I love this record. I've just listened to some many times this year. It's a pretty substantial departure from the post-punk approach they took on their terrific debut "[For the first time](https://open.spotify.com/album/2PfgptDcfJTFtoZIS3AukX?si=Pn-Rz5lPTm-_MBtA445BhQ)", opting for a chamber pop type sound instead. This allows for each of the instruments to have more profound role on the record and they put that to good use. The "Intro" starts like their first album, a fun instrumental but rather than a jam, serves a introduction to the album's sound instead. It transitions into the almost silly "Chaos Space Marines" with dramatic piano and saxophones blasting as the song drives forward. It just sounds like the band is having such fun with this track. It then goes into the amazing "Concorde", containing the understated iconic vocals from Isaac Wood. I just love how the saxophone and keyboard harmonizes on the second half of the song before it builds an emotional climax. "Bread Song" contains more rising saxophones and simple drums and guitar strums. A big highlight of the record falls on "Good Will Hunting", with a pound of synth keys bringing you into the song. The way Issace sing "she has Billie Ellish style, moving to Berlin for a little while" just sounds so cool in his baritone voice. The front half of the album contains the shorter, more single type songs, but the real magic is on the back half. The B-side starts with the truly remarkable "The Place Where He Inserted the Blade", my favorite song of 2022. It opens with somber piano chords and a breathtaking flute before Issac opens with the lines "your scared of the world where you're needed". Issac then belts the lines that I just love to sing along to "How come every time I try to make lunch for anyone else in my head, I get lost dreaming of you, and you come to me". It's just a line that gets stuck in your head. On the first chorus, the flute remains present, but is then replaced by a saxophone on the second first, giving the song more power. After the second verse, the whole band comes in seeing along to the melody, a moment that always overwhelms me emotionally. We then go into the 9 minute "Snow Globe", a slow burn song with motif-esque guitar lines and a swelling violin part. There is some pretty incredible percussion on the back half of the track that really show case that the talent of the drummer/percussionist. Finally we get to the epic finale that is "Basketball Shoes", the only song fitting to end this masterpiece. This 12 minute journey begins with instruments entering the song one by one, with a gorgeous harmonies between the saxophone and violinist. Issac the comes with hushed vocals to accompany the beautiful instrumentation surrounding him. The song the quickly transitions to post-punk sound familar on their first album, but only for brief moment. Each instrument the plays a singular note in order before erupting together playing the same melody. The song then builds tension for the big finale, with echoing drums and Isacc lamenting "in my bedsheets are now wet, with Charlie I pray to forget". The band then just unleashes, giving everything they got as they sing together one last time. Its such a perfect end to a perfect album. This album hits me quite a bit harder following the news that Issac Woods left the band to tend to his mental health. This album almost feels like a goodbye in many ways. Still, I hope Issac receives the help he needs and can live a happy life. It goes without saying that this album is my front runner for not just album of the year, but album of the decade. It's been a lot time since a piece of music has resonated with me as much as the work did. It's something truly special.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/21xp7NdU1ajmO1CX0w2Egd?utm_source=generator" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** The Place Where He Inserted the Blade, Basketball Shoes, Good Will Hunting, Concorde, basically the whole album
