---
title: "Top 25 Albums of 2023"
format:
  html:
    code-fold: true
    toc: true
title-block-banner: true
---

I must say, this has been one of the strangest lists I've ever put together.
I was just having a really difficult time finding music that was resonating with me in the first \~6 months of the year, with a few notable exceptions, which made me a bit nervous about the list.
It's possible that after creating what is probably my favorite list so far the previous year, I was dealing with a bit of a musical hangover.
Still, I was finding throughout my typical musical sources/blogs that there was somewhat of a consensus that 2023 was just a weaker year of music.
But now that I have made my list, I'm actually incredibly happy with how things came out.
The second half of the year was jam packed with fantastic releases that really filled out the list.
Additionally, years in which I'm having a more difficult time finding music tend to lead to me branching out a bit more into other genres, which make for more interesting lists (at least in my opinion).
For the first time, I have two hip hop records in my top 10, which is a genre I've been trying to spend more time it.

I don't think it helped that I was on the go a ton this year, traveling back and forth from New York City a lot this year, traveling to Aruba for a vacation that I was incredibly (so incredibly) fortunate to join my girlfriend's family on, another summer of field work at Whiteface Mountain, and yet another extended trip to Colorado.
This year is also setting up the end of my PhD, with my hopes of finishing up in August 2024, and permanently moving to New York.
Seems anxieties of producing high quality work, whether it was my PhD or this list was somewhat of a theme this year.
I'm very happy with how this list ended up and maybe it's a sign for things to come.

## My Favorite Songs of 2023

1.  Blomi - Susanne Sunfor
2.  The Clutch - Palehound
3.  Bull Believer - Wednesday
4.  Swing (In A Dream) - Squid
5.  Soft Landing - Billy Woods and Kenny Segal
6.  Fire the Editor - James Blake
7.  kisses - Slowdive
8.  2000 Miles - Jolie Holland
9.  Mitski - I Don't Like My Mind
10. Garbage Pale Kids - JPEGMAFIA and Danny Brown

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/0PywVGo37UYQqobfGUsHJ9?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
## 25. Jessie Ware: That! Feels Good!

Sneaking into the list this year is the insanely fun disco/funk record from Jessie Ware.
Jessie Ware really blew up in 2020 with a similar genre of dance music in 2020 with [What's You Pleasure](https://open.spotify.com/album/1CTm3ARqDETSm7GfvNYNJp?si=qum3K8NQQ7iY56cnNfGEAQ), but for whatever reason I never really could get into it.
On "That! Feels Good!", she won me over with just the unadulterated joy found throughout the record.
"Begin Again", a favorite of the year for me is just fantastically put together song with the jangly guitars, piano lines matching the melody, and the prominent horns.
Incredibly fun record.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/17g3sAeWfpHSJlqMHuRAr6?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Begin Again, Free Yourself

## 24. Earl Sweatshirt and The Alchemist: Voir Dire

Earl Sweatshirt is back with another solid project, teaming up with the Alchemist to produce a slow paced, yet often bright sounding record.
I really like Earl's flow on this record, the down tempoed approach is a nice contrast to the bright pianos on the track "Mancala".
"Vin Skully's" beat is such an earmworm, with the simple blues guitar riff, before a super cool transition into "Sentry".
With track list coming in at only 26 minutes, there is no excuse not to give this record a try.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/2jFEoWXPcVtO7MX0j12kZ6?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Vin Skully, Mancala

## 23. Bully: Lucky for You

I'm such a sucker for loud, powerchord driven indie-rock, so there was never going to be a world where I didn't like this album.
What stands out for me is the fantastic lead vocals from Alicia Bognanno and the slight feedback from the guitars combined with synth lines to give each track a fuller sound.
"A Wonderful Life" is a perfect example where the guitars are turned up to 11.
We then transition into the best track on the album, "Hard To Love", containing a ton of fuzzy guitars and feedback that just make this so badass.
This is indie rock at its best.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/0Wl5Z73DtV3cgqf0MLXgxz?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Hard to Love, A Wonderful Life

## 22. Sufjan Stevens: Javelin

Sufjan Stevens finally got me to like a whole album.
For whatever reason, I have never quite gotten why so many people are so enamored with Sufjan Stevens, even understanding some of the incredibly personal and heavy topics his previous works have discussed.
But on "Javelin", I might be starting to get it.
There are just some many beautiful moments throughout the record, whether its the children choir coming in towards the end of "Will Anybody Love Me" or the delicate approach to "So You Are Tired"; a song so delicate it might fall apart at the slightest touch.
When the album released, Steven's announced to the world the album was dedicated to his life partner who had recently passed away which just adds to the soul crushing nature to this album.
A true work of art no one should miss out on.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/2KqSL3vLfyVO7rrZJL9tUs?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Will Anybody Love Me, So You Are Tired

## 21. Yeule: softscars

Perhaps one of the most unique albums I've heard this year comes from yeule, combining elements of rock and metal with glitch pop.
I can help but get this idea in my head that this is "zoomer" music, music for Gen Z. But that probably makes me seem like an old man.
The opening track "x w x" sets the stage perfectly for the rest of the record, with heavy distored guitars and a pretty amazing screamo-esque belt that just awesome.
"softscars" has this groovy beat and ringing digital sound to it that always has my head bopping along.
This is a super unique listen and perhaps points to a sound we could hear more of in the future.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/7t01lwQRDjtEvwiAm88ACH?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** x w x, softscars

## 20. Boygenius: The Record

The famed sad-girl trio is back!
Unfortunately, this album at times feels like a collection of B-Sides or spare songs from their respective solo careers.
The good news?
Turns out that the B-Sides of these stupendously talented songwriters still makes for a really good album.
Interestingly, I find that Julien Baker really stands out on the record, the member I listen to least to.
For instance "\$20" kicks butt, with scratchy guitars and a powerful vocal delivery from Baker.
There are some truly fantastic singles on this record, like the undeniable "Not Strong Enough", whose chorus is just so amazingly catchy (especially when Bridgers and Baker go into their falsettos).
I really like sincerity of "Cool About It", the theme being friends who are unable to discuss an undisclosed problem/fight.
Tons of great stuff here and it certainly will tide me over until the next project of one of these three.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/0e9GjrztzBw8oMC6n2CDeI?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Not Strong Enough, \$20

## 19. Jeff Rosenstock: Hellmode

I'm always on the look out for a good pop-rock record as it's a genre of music that holds a special place in my heart.
This year we have a release from the excellent skaw/punk veteran, Jeff Rosenstock.
While I've been aware of him for a while, this is the first time I have actually dug into a project of his.
This album has everything essential for a punk record; loud guitars, catchy choruses, and tons of angst and unrest.
"Will U Still U" is a strong start to the record with the refrain of "will you still love me after I fucked up" before the song picks up the pace with an almost speed metal-esque drum line, feeds into a fantastic sing-along chorus.
"Head' is a criminally too short track as Rosenstock explores so of the desperate political issues facing the United States that somehow manages to be a ton of fun. There is a ton of great stuff in here for any pop-punk fans out there. If this a genre you love, this is a must listen.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/7Gw4NIOgnylpbryrOJksn9?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Head, Will U Still U

## 18. Jules Olson: Heavy Hitter

This is a first for me, where I actually get the chance to review an album that a friend of mine made, which I think is pretty cool (hi Jules!).
In her debut full length record, Jules skillfully combines soul, singer-songwriter, and folk that showcase some of her biggest musical influences including Pinegrove, John Mayer, and Allen Stone.
"Solid Ground" has such a terrific instrumentation to that serves as a perfect pairing to a damn good vocal performance from Jules (the pedal steel in particular just works so well here).
"Cold" is an instant classic, with a breezy vibe perfect for road trips in your car when you have nowhere in particular to be.
There are some lovely acoustic tracks like "Good Thing" to give the album a melancholy yet cozy feeling to the album.
Fantastic debut from Jules; give it a listen.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/19UjY2U4XG9k2KSNstEk91?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Solid Ground, Cold

## 17. James Blake: Playing Robots Into Heaven

James Blake is really starting to become one of the more consistent artists in music right now.
His early career stuff would always contain amazing tracks but he could never pull it off for entire record.
But now Blake continues his excellent song writing form from albums like the excellent [Assume Form](https://open.spotify.com/album/3VpbXPsAOhcp3duHhkye8g?si=ofREEAE9SrCc1AfK04Qedg) with "Playing Robots in Heaven".
This album serves as a late night EDM album, with danceable yet subdued beats, like on tracks like "Loading".
However, there are plenty of tracks that play to Blake's strengths such as "Asking to Break" with the spacious beats, vocal effects, and his iconic voice.
"Fire the Editor" is right up there with his very best tracks; a beautiful ballad that feels like a lullaby as much as anything.
It's also one of James Blake's best vocal performances in his career.
The album closes with a dreamy piano ballad and a hushed ambient track as if to represent the end of a night out.
Another great project from an artist who is really growing on me.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/2ZwNcWl8h9blysDE8i4juL?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Track:** Fire the Editor, Asking to Break

## 16. Say She She: Silver

You will have a hard time finding a more fun funk and soul record from this past year than Say She She's "Silver".
This album is just chock full of jams that are guaranteed to have you bobbing you head alone.
They waste no time with groovy "Reeling", with incredibly fun rising falesseto vocals weaving in and out of the track.
It doesn't get anymore whimsical than the wonderfully silly "Astral Plane", as they hope to meet their lover on another plane of existence (hint, its the Astral Plane).
This is a track that has been on repeat a lot for me since the album dropped in October (and a great soundtrack for my bike rides to work in Colorado).
"Think About About It" has a verse that [Khruangbin](https://open.spotify.com/track/24ntSW3QVJzR79lHAAOTaY?si=e8a24a02685d422b) would have been proud of, that I find just so delightful.
The album runs a bit long with 16 tracks coming in at 1 hour and 6 minutes, but their just so many gems on this record that it's hard to blame them for including as many tracks as they did.
A perfect album to put you in a great mood.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/043vgwukOxX7bcL4VuMX10?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Astral Plane, Think About It

## 15. Jungle: Volcano

This is probably the only album that was able to out-groove Say She She.
I really enjoyed Jungles [Loving in Stereo](https://open.spotify.com/album/3xuvOKpNqynROqZt8Tvcfh?si=MJVIUEJ1SIu8_LfzuQ5S8Q), contain tons alternative funk tracks and a favorite song of mine from 2021, "Romeo".
They return an excellent follow up on "Volcano", with a stylistic change opting for more female vocals with lush harmonies and use of horns and flute that take their sound to another level.
This album is just banger after banger of energetic disco and funk tracks.
"Dominoes" was an instant hit with me with, containing an incredibly infectious guitar line that gets stuck in my head.
The playful vocals add to the vibe and I just love how the layered vocal harmonies on the second chorus sound.
Such a cool moment on the track.
"Back on 74" sounds like a Gorillaz Plastic Beach era song if they decided to add doowop vocals to the track, making for another great highlight on the record.
They album contains a bunch really fun features like Channel Tre on "I've Been in Love" or Bas on "Pretty Little Thing" to add something a little different throughout the album.
Another incredibly fun record from a fun band.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/5xnXOCf5aZgZ43DgGN4EDv?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Dominoes, Back on 74

## 14. Wilco: Cousin

As with any Wilco album, I must disclose that Wilco is my all time favorite band and really can't do much wrong in my eyes.
Still, I truly think this a yet another fantastic release from the veteran band.
There was a lot of great stuff on their previous release [Cruel Country](https://open.spotify.com/album/5prfZewHLWnEMaWdDdgEb5?si=TGdUgCuKRPOGM6t7JMXg3Q), but had too many mediocre tracks due to the attempt at a double album On "Cousin", they cut out the fluff to make an album that I think of as a sister album to the cult classic [A Ghost is Born](https://open.spotify.com/album/1RCxMEn5jFeUWbof3vy8oC?si=LP8rtp9mTV-uAFeDeye2qA).
While maybe not as experimental as their most acclaimed works, their are great production moments and band adjusts throughout the album.
Like on "Infinite Surprise", the ticking clock adds a certain tension to track, before it finally fading to the background as the rest of the band comes in.
On "Evicted", the track starts off as what seems like simple Jeff Tweedy track acoustic track, but layered guitars start filtering into the track and by the end have the song has changed so much, it makes you wonder how you go there.
"A Bowl of Pudding" reminds a little bit of [Muzzle of Bees](https://open.spotify.com/track/3AJwzV9YlIn8PfxDnEGApp?si=b11a63fe3fa04cff), with its echoing acoustic finger picking and delicate vocals from Jeff Tweedy.
"Pittsburgh" is the major highlight on the record for me, as it transitions in and out of a simple acoustic track into a explosion of guitar feedback and synths.
Wilco continue to show that they aren't just a dad rock band of the past, but continue to have fresh ideas to contribute to world of music.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/1KZy1Oll0Cnnakyy6X92Wn?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Pittsburgh, Cousin

## 13. Geese: 3D Country

Despite it's fairly straightforward sound, "3D Country" has been such a difficult album for me to put my finger on.
At first, I wasn't even sure I liked it, but I kept finding myself coming back to it.
At times, the record feels like a relic of the past, a soft rock album that probably would have been popular in the 70s.
Yet the album also feels out of control and insane, largely due to some undeniable vocal performances from Cameron Winter like on the title track or "See Myself".
The album starts big on the badass "2122", with Winter's vocals taking turns with some southern rock guitar riffs.
But they pivot sounds all the time on the record.
The title track has such a wonderful vocal melody backed by some almost gospel harmonies that give the song so much charm.
So many of the songs on the album Geese just absolutely goes for it, like on the energetic Undoer or Mysterious love.
This has honestly been a fairly tough album to write a review about as I still don't know quite to make of the band.
There is one thing that I know for sure; this is a damn good album from a damn good band.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/475CtqaU2OY24xBvIekWV6?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** 2122, 3D Country

## 12. Shame: Food for Worms

Shame are back with another fantastic punk/post-punk/indie rock record filled with tons of emotion.
I really enjoyed the hectic but sincere [Songs of Praise](https://open.spotify.com/album/3ZtngTnZwbWMAdzcpKWgXH?si=9xZ_ec9wR7WVImXKkpDm0Q), particularly tracks like "Concrete" and "One Rizla".
Here they return with "Food for Worms", backing off just slightly from their punk sound in favor of a more indie rock sound.
Despite this change, they didn't lost an ounce of the sincerity that made previous work so special.
There is the great optimism to the opening track "Fingers of Steel" despite a more downbeat lyrical content of regretting the circumstances that a person has found themselves in.
The vocals from Charlie Steen are perfect; he's not a classically trained singer by any means, but they rough around the edges approach to his singing are a critical part of what makes Shame, well Shame.
Steen is capable of great belting, like the tracks "Alibis", but is capable of more tender moments like on the best track on the record "Orchid".
I love the lower energy the song start with before it finally ends with an army of guitars and heavy bass to bring the song home.
Such a great moment on the record.
"Adderal" has this great sing-along quality to the chorus, with the call and response vocals from the Steen and the band.
It honestly so sweet sounding, despite being about the inappropriate use of adderall.
The album closes stellarly with "All the People", acting as summary for the whole record.
This album got a ton of love from the indie community upon release, and I completely get it.
There's just so much to get behind on this album.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/6A3JJrCJO2TXZ9Vfy3tIbW?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Orchid, Fingers of Steel

## 11. Blonde Redhead: Sit Down for Dinner

Just missing out on the top 10 is the lovely "Sit Down for Dinner" from Blonde Redhead.
Despite putting out music since the 90s, this is the first project that I have listened from this group; and it's a wonderful introduction.
There is this great mystique that shrouds over the album that I just find so intriguing.
The album strikes a great balance between dream-pop and indie rock aesthetics as the veteran musicians show have shown they honed their craft.
I think part of that is down to what I find is excellent production.
I love the slight reverb thrown on just about every sound that you hear on the album, but without over-saturating things to the point where you can't distinguish any of the sounds.
I also enjoy that the lead singers alternate each track, keeping the album from sounding stale at any point.
I think the album works best consumed all together, but that prevent so fantastic singles like on "Not For Me".
I find the vocal melody so beautiful coupled with the acoustic guitar, subtle background vocal harmonies, and echoing lead guitars.
The excellent "Melody Experiment" quickly follows, with these great woozy guitars and subtle noises added into the background, making for a really interesting listening experience.
There are some proper B-Side tracks on the album that are bit slower, but greatly add to the character of the album.
"I Thought You Should Know" feels like it could be a song in the movie [Chariots of Fire](https://en.wikipedia.org/wiki/Chariots_of_Fire).
"Via Savona" gently closes the album with much of the same dreamy aesthetics that made this album great.
This album grew a lot on me after repeated listens, and I find it is best enjoyed to with a good set of headphones.
Give this record a spin, especially late at night.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/7GfokyxLDkBsgR9gUmEbRq?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Not For Me, Melody Experiment

## 10. Jolie Holland: Haunted Mountain

If there was one word I would use to describe this album, it would be "Magic".
There are just some artists that inexplicably take a relatively sparse sound and just make it so special; artists such as [Nick Drake](https://open.spotify.com/track/6meH4I9A4WZtD3z8hnQKqr?si=1a335c6e29fa407c) or [Angel Olsen](https://open.spotify.com/track/4hJEhCACCeA8U4CyTP4BDw?si=f455853195954f7f) who just capture this magic like no other.
"Haunted Mountain" is filled with song with the quality.
The release of the album was also right in the middle of fall and I can think of few better cold weather companions than this record.
I think a big part of the magic of this album comes from the weary vocals from Holland, symbolic of a 2 decades long music career that add a layer of genuineness to each track that is hard to imitate.
"2000 Miles" is a perfect opener for the album and a truly beautiful track as it opens with the devastating line "I couldn't sing a high note, or put on my shoes, without remembering you".
There is such an expert use of space through the album, with the sparest alt-country and americana band arrangements that bring Holland's words to the front of every song.
"Highway 72" features a comfy duet with a musical hero of mine, Buck Meek of Big Thief.
There is so much chemistry between the two that you would have thought they have been life long friends.
The title track is subtle country ballad that I can easily imagine Jolie Hollarnd playing in some middle of nowhere western bar.
"Orange Blossoms" is a dark track, pointing out that that mother nature will be here, whether humans are or not.
I really love how Holland closes the record on "What It's Worth".
The song is a bit dreamier than the rest, with the hushed strumming of rhythm guitar with a single notes being plucked from the lead guitar.
After finding this album, I plan to do a deep dive into Jolie Holland's discography as I haven't found a singer-songwriter who has resonated with me like this in quite a while.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/2CVC0KMuJ73P8AMLToOkuQ?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** 2000 Miles, Haunted Mountain, Highway 72

## 9. Everything is Alive: Slowdive

I find it pretty cool that a veteran group like Slowdive can take an extended, 2+ decade long hiatus, and then return making some of the best music of their career.
Their previous [self titled record](https://open.spotify.com/album/1qDA0jVhj4ZTjGHmpbmmwa?si=IUc4bsOGSUyKhFDUc_JFNA), was an incredible dream-pop/shoegaze record that rivals almost everything Beach House have put out, and I'm adamant [Sugar for the Pill](https://open.spotify.com/track/0eVz3hV2xOXdneGpnWDFpb?si=b3f340428e8847ac) is one of the best songs of the 2010s.
The group returns with the excellent "Everything is Alive", involving sounds that don't stray too far away from previous work, but still manages to keep this record distinct.
"shanty" opens the album strongly, with the pulsating synth line, distorted guitars, and some a super cool use of harpsichord.
"prayer remembered" is a methodical instrumental fill as each instrument takes its turn fading in and out of the track.
They pick up the pace with,"alife" is a track reminiscent of "Star Rover" showcasing these great cascading guitars on the chorus; real highlight on the album.
Far and away the best track on the album is "kisses', the lead single, with a lead guitar part that always finds a way to get stuck in your head. This song is absolutely perfect for late night driving. Their are other dreamy shoegaze tracks on the album like"skin in the game" with an amazing tapestry of guitars, especially on the backend of track, or the urgent sounding "the slab". These guys have been making music like this for a long time now and rather rest on their laurels, continue to put out fantastic dream pop records. Check this record out with (like all of there other work) with a good set of headphones, late at night.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/2jSmcj39eQiU76EbMGuxS0?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** kisses, skin in the game, alife

## 8. Andy Shauf: Norm

Andy Shauf has done it again with another fantastic narrative album, but with quite a bit darker than sweet [The Neon Skyline](https://open.spotify.com/album/41M6R2mWLgqU9aKFUvZv8S?si=Sf-9Iz0hRqCyrzIEWcqEqQ).
I must admit, I this album took some time for me to come around.
I was more expecting the lush chamber pop arrangements on the incredible [The Party](https://open.spotify.com/album/35FWLG8Ysjj1BF3sx4F6zM?si=8jdLTYMoQN-RpH6V5umK9g) or the fun acoustic story telling on the Neon Skyline.
But here, Shauf changes his style, with arrangements that are while beautiful, feel just a bit off.
However, once I dug into the lyrics further it all clicked.
"Norm" follows the story of, well Norm, as his love for a girl turns to an unhealthy obsession.
We start the record with the delicately arranged "Wasted on You", from the perspective of God, worrying that all of the love he shares with humanity is going to waste, before we are introduced to our protagonist, Norm.
Norm is day dreaming on "Catch Your Eye" hoping for a chance encounter with the woman he loves.
He begins to stalk her, calling her telephone but finding himself unable to speak.
God tries to steer Norm clear of these "wicked ways" by speaking to him in his dreams but to no avail.
On the eerily beautiful "Sunset", Norm finally gets his chance, running into his love at a Halloween store, with the two hitting it off, before she comes out to the parking lot to find her car is missing.
To her own demise, she accepts the ride, and as she realizes something is up, she uncomfortably asks "are we leaving the city?", never to be seen again.
This track brings the body count in the Shauf's music catelog to 6 (certainly higher than most artists).
The repetition of the phrase "this isn't the end" only stands to make the song ever creepier.
The album closes with a couple of tracks explaining that an ex of the ill-fated woman was a tow-trunk driver and towed her truck the day she was kidnapped, and growing concerned when he doesn't hear from her.
Norm (the record) is another amazing example of Shauf's knack for unique and impactful storytelling.
Like many other artists I love, his songs are often greater than the sum of their parts, including the simplicity in most of the stories he writes.
These traits in his songwriting make him unique and it should be no surprise they are a major reason why he is one of my all time favorite songwriters.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/0TaN6TZg6BpT0lQNJAhGrC?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Sunset, Wasted on You, You Didn't See

## 7. Billy Woods & Kenny Segal: Maps

Billy Woods has been on my radar for a little while now as one of the biggest names in underground rap and is just adored in basically every online music community I'm aware.
I finally decided to give him a close listen and I'm now asking myself what took so long.
Here, Woods teams up again with the producer Kenny Segal following up their previous beloved collaboration [Hiding Places](https://open.spotify.com/album/0HmKhR7Umt3ACs52ZLnKyK?si=UQrNts0MQHGX1vvXSJTnUA) to create one of the best hip hop records of the year on "Maps".
There is this amazing sluggishness to the majority beats throughout the album that works so well with Woods cadence and flow.
It honestly amazes me how much Woods can change his style with these downtempo beats.
The production throughout the record is fantastic.
"Soft Landing" is my favorite track on the album, with the jangely guitars and heavy bass.
The way Woods nonchalantly asks about drinks before jumping right into the track is such a cool moment.
With 17 tracks, this album could have felt like a drag, but with only 5 of the tracks lasting longer than 3 minutes, the record moves on before you have a chance to get bored.
"Babylon Bus" is another highlight, starting pretty subdued before building tension with a great feature from ShrapKnel, that finally erupts with strings and horns.
This song then transitions sublimely into "Year Zero", containing a crazy Danny Brown feature (who seemed to be showing up everywhere this...).
The lyricism throughout this album is honestly so abstract that just about every track requires thorough listening to fully digest what is being said.
Despite the down tempo production found on this record, there are some lighter moments like on tracks like on "Facetime", with a great hook from Samuel T. Herring, or the jazz flute on "Waiting Around" (with a great feature from Aesop Rock).
I feel like I'm going to continue to find things in this album that I didn't notice before for the months to come.
Any hip hop fans should spend time with this record, because there is a ton to digest.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/3VoX4iyvy7et6Qt47e2XwS?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Soft Landing, Babylon by Bus, Facetime

## 6. Wednesday: Rat Saw God

My introduction to Wednesday is kick-ass, with "Rat Saw God".
The 5 piece indie-rock/garage rock band has produced a collection of 11 songs that are about as vulnerable as you'll hear from this past year.
The first thing that you noticed (and what immediately peaked my interest) is just how loud this record is.
They combine all kinds of genres of rock from punk to noise rock to grunge with even some slight country twang with the inclusion of pedal steel (which might be a growing trend in music pointed out by Jonah Krueger at [Consequence of Sound](https://consequence.net/2023/10/pedal-steel-country-indie-mitksi-wednesday/3/), which is a welcome development for me).
Beyond the instrumentation is the subject matter, telling stories of drug and alcohol addiction/abuse throughout.
A perfect example is on the truly excellent (and one of the best songs of the year) "Bull Believer", as the first half of the song describes the horrors watching someone you love fall to addiction.
The second half invokes of a shitty relationship, watching your boyfriend play Mortal Combat as you sit on a coach on New Years Evve with a nosebleed, before erupting into a huge mess of guitars, as the lead singer Karly Hartzman belts "Finish Him" that collapses into visceral screaming (best vocal performance of the year).
"Chosen to Deserve" a Drive-By Truckers inspired track (Hartzman told Apple Music) that tells the story of Hartman's friends taking Benadryl to get high, as one of the friends take too much and had to get their stomach pumped.
I find the framing of this song interesting, using this story as if to say take me as I am, warts and all, and is thankful that she is "the girl you have chosen to deserve".
There are so many times that album just goes for it with guitars like on "Bath Country" or "Quarry".
I really like closing track "TV in the Gas Pump" a great way to close the album as the band steps back from the louder for a more laid back rock sound.
I find it a nice way to ease out of what, at times, can feel can be an a pretty intense album.
This is a truly phenomenal rock record that demands repeated listening.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/1oTR3aC0jYmwUlr9duBi05?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Bull Believer, Chosen to Believe, Bath Country

## 5. Mitski: The Land is Inhospitable and So Are We

Mitski has always been a slightlt frustrating artist for me.
She is so clearly a talented songwriter and performer who has (deservedly) amassed a huge following.
But a thing that always bugged me about her songwriting was how short the songs were.
Albums like [Be the Cowboy](https://open.spotify.com/album/42cH7mrkfljkqkxA2Ip9Xq?si=U3wQ-EoiS8mDOb1AKKt2FQ) have so many great ideas on them, but the songs end before they can leave a real impact.
On "The Land is Inhospitable and So Are We", there is no such issue and the results lead to one of the best indie-folk records of the year.
Here, Mitski employs much of the same intimate songwriting on previous project with some alt-country additions (including more pedal steel! Big year for pedal steel).
"Bug Like an Angel" starts the album almost playful, with choir singing along with Mitski, but don't be fooled, as the song has pretty sad lines like "as I got older, I learned I'm a drinker. Sometimes a drink feels like family".
"Heaven" is this great country-style ballad, where Mitski just wants to carve out a piece of heaven with the one she loves.
We then transition to my personal favorite track on the record "I Don't Like My Mind".
I just love the reverbed acoustic guitar strumming on the track, as it backs up a vocal performance that Mitski knocks out of the park.
The song is Mitski at her most vulnerable, talking about eating a whole cake before getting sick and throwing up, contributing to a cycle of intrusive thoughts that leads to moments like this.
There are a ton of beautiful and tender moments on the record on tracks like "The Deal" or "I'm Your Man", that has this really gorgeous choir harmonizing (with some slightly disturbing dogs barking in the background).
"My Love Mine All Mine" has turned into a mega hit (sitting at 345+million streams as of December, 2023), which a truly magnificent love ballad.
The album's closer "I Love Me After You" , hearkening back just a bit to some of Mitski's earlier work that was guitar focused like on [Your Best American Girl](https://open.spotify.com/track/7g5qe8VITjr13RIe8uM2p6?si=f7e5111018944874) (a damn good song), with almost sludgy black metal chords to close out the album.
Is this possibly a hint on the sound of a future album (I hope so)?
I tend to not like getting negative in my reviews of albums (an album that makes the top 5 nonetheless) but Mitski extending her songs just by 20-30 seconds is all I really needed to connect with her music.
All I can say is I'm looking forward to future her projects.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/2Cn1d2KgbkAqbZCJ1RzdkA?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** I Don't Like My Mind, I Love Me After You, Heaven

## 4. Reverand Kristin Michael Hayter - SAVED!

A quick warning, as I'm going to discuss some pretty dark things including sexual assualt and abuse.

Kristin Hayter has released on the most terrifying listening experiences I've heard in my life on "SAVED!".
Hayter had previously released music on the project [Lingua Ignota](https://open.spotify.com/artist/3Q2RrKEOBdkWI2MJQgdt84?si=zddgW_h7TOuxFVXWp_XE1A), combining heavy religious themes with dark and distorted soundscapes (a genre known as [dark wave](https://en.wikipedia.org/wiki/Dark_wave)).
She had developed quite a cult following, but the music is pretty heavy and abstract, and I had always found it a bit inaccesible.
Her most recent project, [SINNER GET READY](https://open.spotify.com/album/06wtf2TCkmyTgS1yZGiSr5?si=C_SickINQOmUmKIWOJm-7A), I really began to pay attention more to her music, largely due to her earning an incredibly rare 10/10 from the [Needledrop](https://www.youtube.com/watch?v=g6S0XHGKzUU) (only the 7th album to do so after what seems like 1000+ reviews).
During an interview with [Anthony Fantano](https://www.youtube.com/watch?v=0Bi39S0mBck), Hayter revealed that she had been in an abusive relationship that led to a spinal injury requiring surgery and had to be partially crowd sourced by donations from her fans.
SINNER GET READY's theme was based around this abuse, making for an utterly painful listen.
Fast-forward to 2023, Kristin Hayter has retired Ligua Ignota and began releasing music under her own name.
SAVED!
serves as Hayter healing process, after truly traumatic events, using religion as way to recover.
The stylistic choices are quite a bit different than previous records, approaching the album with traditional gospel choir tracks with simple instrumentation, including stand up piano, loose vocal harmonies, and guitar.
The production is really where this album stands out, with songs sounding heaviliy distorted and fuzzy, as if you would find the record on cassette in an old, abandoned attic.
For instance, on the opening track "I'M GETTTING OUT WHILE I CAN", the song cuts in and out so aggressively that on the first listen, I had to check to make sure my headphones weren't broken.
Combined with the strong religious themes throughout the album (like bluntly stating all of her friends are going to hell), it makes for a disturbing listen.
This album honestly would serve as an amazing horror movie soundtrack about a religious cult.
Many of the tracks like "IDUMEA" have these ominous banging piano chords that put a pit in my stomach.
Yet, despite all of these uneasy feelings have, these songs contain the theme of being saved by God.
As someone who has been nonreligious his entire life, it's hard for me to understand the complicated relationships people can have with religion, even if it has caused them harm.
Religion may have been something has helped Hayter to begin to heal, and if that is the case, it's a wonderful thing.
I think the album closer "HOW CAN I KEEP FROM SINGING" captures my feelings on the album best.
The song starts off beautifully, starting with just Hayters beautiful singing and a simple piano accompaniment.
As the track goes on, you begin to hear Hayter speaking in tongues, that only get loader and more pained, making for a creepy duet.
By the end of the track, you are left with just Hayter sobbing and coughing as her voice gives out.
I have yet to really wrap my head around this track, but I currently read as Hayter beginning to find peace but those demons from her trauma remain.
I can't tell you that this is a fun or enjoyable listen.
But few pieces of art have left an impression on me quite like this.
If you can stomach it, I highly recommend giving this a listen, and then probably never listen to it again.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/1IdsqGbN3oB6kAM1Iq0QnC?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** HOW CAN I KEEP FROM SINGING, I"M GETTING OUT WHILE I CAN, ALL OF MY FRIENDS ARE GOING TO HELL

## 3. JPEGMAFIA & Danny Brown: SCARING THE HOES

If you need a palate cleanser after "SAVED!", then this might be a good option.
JPEGMAFIA and Danny Brown team up to make the craziest, silliest, bat shit crazy hip hop/glitch hop record of the year.
There was a significant period of time this year where I thought a record entitled "SCARING THE HOES" was going to be my album of the year; and it got damn close.
The title refers to the unconventional hip hop music that both artists have made in the past that might be considered too weird for a lot of people.
They then decide to make a record specifically designed to "scare the hoes".
This album honestly made me laugh more than anything, not because it wasn't good, but the fact that is was THIS good.
The production is just incredible, combining all kinds of sounds and samples that don't seem like they belong together.
"Steppa Pig" changes tempo and tone some many times, with blown out bass and synth lines.
I love the difference in how Danny Brown and JPEG approach their verses on this track (and basically every other track) , with Brown acting silly and snotty while JPEG appears to take things more seriously.
"Garbage Pale Kids" is my favorite on the record, containing a sample from commercial from the Japanese meat packing company Nichro (of all things) as these great distorted guitars kick in.
The detestably entitled "Fentanyl Tester" is an insane remix of Kelis's [Milkshake](https://open.spotify.com/track/4LmzPJDil70LpiApWfOI6O?si=27c9dfd2efc44db0) where JPEG just goes off on the back half of the song.
Danny Brown's line on the track "I'm a big dog like Marmaduke" never fails to make me laugh.
I feel like I'm just going down the tracklist and pointing out this that I like on each song, but honestly there isn't a dud in the bunch.
Every song has a creative beat that is crazier than the last.
Like the big horns blasts on "Burfict" or on the track "Orange Juice Jones", which just sounds like Danny Brown's vocals were accidentally put on top of someone else's song.
"God Loves You" is another favorite of my, starting with a gospel ground before the blown out basses and drum kit join the track, making for a pretty hype song.
SCARING THE HOES is the most fun I've had with a record this year, with its twists and turns in production, and the always Danny Brown giggles found throughout.
I think JPEGMAFIA and Danny Brown accomplished the task the album title i

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/3u20OXh03DjCUzbf8XcGTq?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Garbage Pale Kids, Steppa Pig, God Loves You, Kingdom Hearts

## 2. Susanne Sundfør: blómi

If SCARING THE HOES isn't your vibe, can I interest you in some stunningly beautiful singer songwriter music from Susanne Sundfør?
Susanne Sundfør is known for making delicate chamber pop and folk tracks (though also has an unexpected synth pop/electronica record, [Ten Loves Songs](https://open.spotify.com/album/0pOyUME049kbscTdJ0p8Rt?si=fUJA6MbYQTWi8bkP3HCYPQ)), coupled with her incredibly beautiful voice.
On "blómi", she combines this characteristics with jazz and classical elements to make a truly breathtaking record.
The album opens with a spoken word/meditiation piece, combined with some ambient noise.
It's a strange choice but adds intrigue to the record and I personally love it.
The record begins in earnest with the dreamy "ashera's song" with Sundfør's soaring vocals.
We then move to my song of the year, the title track.
There are few songs I found myself coming back to more this year than blómi.
There is just so much to love on the track, like the optimistic messaging, the great piano chord progressions, or the lovely saxophone solo during the bridge.
The vocal melody is just so infectious (especially the repeated line "nobody told you" ) and I always find myself singing along.
Just a breathtaking track.
"rūnā" is another highlight, with its sweet acoustic guitar strumming that just feel so bright and full of life.
"fare thee well" serves as a goodbye track to a friend or loved one, but in line with the rest of the album, there is hope and closure in the track that implies that this goodbye might be a good thing.
This is yet another dynamite vocal performance from Sundfør.
The album moves into the incredibly fun "leikara ljóð", starting off as a clapping acapella track with these gorgeous gospel harmonies, especially the on lines like"break the ice and drown me" that almost remind something The Beach Boys would do.
The song just continues to build before more instrument joins in to close the track out on a high.
There is this kind of silly spoken word track (in German no less), "Ṣānnu Yārru Lī", layered with ambient noise and jazz flutes, that works perfectly as way to prevent the sound of the album from growing stale.
The final full track on the record, "náttsǫngr", is another stunning piano ballad where Sundfør just nails the vocal part yet again.
I feel like a broken record here, but her voice is just such a gift.
This album perhaps isn't the most groundbreaking thing around, but the songwriting and vocal performances are just undeniable.
Few works from this past year will bring you more peace than this record.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/0Cq0t6HFg2UeAEqwED7ezE?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** blómi, leikara ljóð, fare thee well, náttsǫngr

## 1. Squid: O Monolith

Squid are quickly becoming one of the best post-punk bands in the genre, following up their fantastic full length debut [Bright Green Field](https://open.spotify.com/album/219LGvgmAhhwlfc3unDhUt?si=F5AqkrZNQHyYkPyZjAq_Wg).
This album kind of snuck into the number one spot, as it didn't immediately grab me, but I just kept coming back to it.
There are so many different things happening sonically that each track requires repeated listens to fully appreciate each detail.
We open with my favorite track on the album "Swing (In A Dream)", starting with a simple synth line before some crazy chord progressions and guitar lines emerge.
This is a key feature of the record, with nontraditional melodies that alternate between post-punk and noise rock, constantly keeping you on your toes.
The song builds amazingly to its euphoric end, with these great blown out synths and soaring trumpet harmonies (a great part of their sound they brought back from their previous record).
In "Devil's Den", they show off their expanded sound, introducting some really pretty jazz clarinet and flute, before swiftly moving into a cacophony of chaotic guitars and some unhinged vocal delivery from Ollie Judge.
I have no idea how he does it, but he finds a way to sing at the top of his register without really sounding like he's singing or screaming.
It makes for some really iconic vocal performances that are a key to Squid's sound.
" Siphon Song" has this bizarre voice production on Judge's vocals that in most cases would sound kind of stupid, but someone how works perfectly in the track, as the rest of the band slowly builds in the background with a haunting group chant.
We then move to "Undergrowth", a song that is down right groovy, despite it's minor tonality and another ionic but unhinged Judge vocal performance.
I adore the fast strummed guitar parts in the middle of the track; they add this great tension that fits the track perfectly.
"The Blades" is another absolute highlight for me.
It contains is this amazing urgency right from the get go, with up tempoed drumming and bright guitars.
The song just builds and builds in bunch of subtle ways, before the track as just explodes into life, becoming one of my favorite moments in music this year.
Another strength of this album is its run time.
Over half the songs are longer than 5 minutes with only track coming in under 4 minutes, allowing for each track to take its time developing.
And yet, the album run time is only 41 minutes, preventing things from dragging, and making the record more accessible.
By the time you get to the brooding "After the Flash" you are well past the halfway mark of the album.
Squid bring the record home expertly with the final two tracks.
"Green Light" starts out hectic, with crazy guitar lines and vocal performances.
But the song relaxes halfway into the track, with legitimately beautiful guitar+clarinet harmonies that really stick out after being in the middle of all of the albums craziness.
The final track.
"If You Had Seen The Bull's Swimming Attempts You Would Have Stayed Away" (what a track name by the way) is great way to close the record, employing many of the techniques that have made previous tracks so special.
I really like how the rest of the band joins in on the vocals at the end, really highlighting what a team effort this album required to make; it's a really nice moment.
I've written a lot about this record, but I still feel like I haven't done the sound of it justice, with all its beautiful controlled chaos.
There is no doubt in my mind that this is my favorite record to come out this year and certainly a favorite of this decade so far.
All I can say now is give this album patience, and it will greatly reward you.

```{=html}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/6El4L0QbF7grZlJmpv7KPI?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
```
**Key Tracks:** Swing (In A Dream), The Blades, Overgrowth, Green Light
